### ISSUE TITLE
Offline payment checkout database error due to status=null

### ISSUE THREAD

**Issue by jclee100** [lunarphp/lunar#1006]
- Lunar version: 0.2 (Livewire starter kit)
- Laravel Version: 9.5.2
- PHP Version: 8
- Database Driver & Version:

### Expected Behaviour:
Offline payment can complete checkout

### Actual Behaviour:
Database error when trying to complete offline payment because status is null.

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'status' cannot be null
update `lunar_orders` SET `status` = ?
```

See: packages/core/src/PaymentTypes/OfflinePayment.php line 24

Looks like the config from config/lunar/payments.php is not being registered.

### Steps To Reproduce:
Checkout with offline payment

**Comment by wychoong** [comment]
this should be raised in the livewire-starter-kit repo

provide content of your
- config/lunar/payments.php 
- .env
- app/Http/Livewire/CheckoutPage.php
- resources/views/partials/checkout/payment.blade.php
