### ISSUE TITLE
Association display behaviour is strange

### ISSUE THREAD

**Issue by CWFranklin** [lunarphp/lunar#1077]
- Lunar version: 0.2.7
- Laravel Version: 9.32.0
- PHP Version: 8.1.10
- Database Driver & Version: mysql

### Expected Behaviour:
Unsure

### Actual Behaviour:
No associations show.
When "show inverse" associations is ticked, two (duplicate) items are shown.
When "show inverse" associations is unticked, one of the items remains.

![image](https://github.com/lunarphp/lunar/assets/3866304/eed212ee-177a-4bd0-be27-31f0f4c93945)
![image](https://github.com/lunarphp/lunar/assets/3866304/8a1eae9b-a78e-4868-b7ff-59913f7e3a8a)
![image](https://github.com/lunarphp/lunar/assets/3866304/c787a298-ec96-46f1-95c5-855cb84165d8)

On page refresh, the list is blank again.

Removal behaviour is still a little weird and possibly classed as a separate bug (see [other issue](https://github.com/lunarphp/lunar/issues/1076)).

### Steps To Reproduce:
Create two products.
First product association created with second product.
Navigate to second product.
Scroll to view associations.

Edit: I have also reproduced this behaviour in 0.3.0.

**Comment by alecritson** [comment]
Sounds like it could be an issue with Livewire's DOM diffing 🤔

Usually this happens if a `wire:key` is missing in a loop.

**Comment by alecritson** [comment]
@CWFranklin Franklin, this should be resolved in the `main` branch and resolved when `0.4` is released, if afterwards it's not then feel free to reopen.
