### ISSUE TITLE
Table not found when setting parent_id on collection model and attempting to create

### ISSUE THREAD

**Issue by dewebdesigns** [lunarphp/lunar#1088]
- Lunar version: 0.3.0
- Laravel Version: 10.12.0
- PHP Version: 8.1.14
- Database Driver & Version: Mysql 8.0

### Expected Behaviour:

Setting the parent_id on a collection creates a new collection successfully.

### Actual Behaviour:

Getting an SQL error: `Base table or view not found: 1146 Table 'dev.collections' doesn't exist` - The database prefix is not set. It should be: `dev.lunar_collections`

From the logs, this is due to the NodeTrait on the collection class hitting the setParentIdAttribute() function.

### Steps To Reproduce:

```
$first = Collection::create([
    'attribute_data' => [
        'name' => new Text('test')
    ],
    'collection_group_id' => 1,
]);

Collection::create([
    'attribute_data' => [
        'name' => new Text('will fail')
    ],
    'collection_group_id' => 1,
    'parent_id' => $first->id,
]);
```

**Comment by glennjacobs** [comment]
This isn't a bug. You need to ensure you are using the nested set package to properly associate collections. 

See the docs for collections and a link to the package we use.
