### ISSUE TITLE
Product Variant's option remains in DB after removing all variants of product

### ISSUE THREAD

**Issue by jclee100** [lunarphp/lunar#1098]
- Lunar version: 0.3.0
- Laravel Version: 9.52.8
- PHP Version: 8.1.2
- Database Driver & Version: MySQL

### Expected Behaviour:
After disabling variants, all corresponding options for the product should be removed.

### Actual Behaviour:
After disabling variants in a product with variants, the option of the remaining variant still has option associated. lunar_product_option_value_product_variant still has the entry for the remaining variant. There's no way to delete the entry through admin hub.

Separately, if using starter kit, the product option is still selectable on the shopfront product page. 

### Steps To Reproduce:
1. Add 2 variants to a product
2. Disable variants using the toggle
3. Check lunar_product_option_value_product_variant (or if using starter kit, the product option is still selectable on the shopfront)

**Comment by wychoong** [comment]
`$variantToKeep->values()->detach();` probably would solve the problem

https://github.com/lunarphp/lunar/blob/4e14b2e59a796b2ba785aa8e782ef645339cdef1/packages/admin/src/Http/Livewire/Components/Products/AbstractProduct.php#L405-L406

but if you are building your own storefront or using the starter-kit, you can workaround with only showing variants selection if `$product->variants()->count() > 1`
