### ISSUE TITLE
Discount performance

### ISSUE THREAD

**Issue by ryanmitchell** [lunarphp/lunar#1103]
- Lunar version: 0.3.0
- Laravel Version: 10.13.5
- PHP Version: 8.1
- Database Driver & Version: MySQL 8

### Expected Behaviour:
Do you have any plans to improve discount performance? At the moment it's structured that all active discounts in the appropriate channels and groups are loaded in every page load, which is resulting in over 1000 extra database queries for us. As you'd expect that comes with a performance hit.

Could the query be optimised to only return those that have no coupon required or where the coupon matches? 

Another optimisation would be to provide a way of those only being loaded in on certain pages - eg we don't display the cart value on every page, so we dont actually need to load in discounts anywhere except for the basket and checkout pages.

**Comment by alecritson** [comment]
Hi @ryanmitchell I've started a draft PR which I'm hoping will address these performance issues, I tested on one of our client sites and it did indeed take the number of queries down quite considerably. I'd be interesting to know your thoughts.

**Comment by ryanmitchell** [comment]
Thanks @alecritson. This has helped a huge amount! Back down to a reasonable number of queries again.
There are a few duplicate queries coming from shipping tables, but I can pick those up with you separately.

**Comment by alecritson** [comment]
@ryanmitchell This has been merged into `main` and will be in `0.4`
