### ISSUE TITLE
Unable to login in Hub : The POST method is not supported for route hub/login.

### ISSUE THREAD

**Issue by parthagorai** [lunarphp/lunar#1124]
I have installed in my local Ubuntu 22.04 Laptop but i am unable to login in hub. Please help me to solve

https://flareapp.io/share/yPa2REY7#top

- Lunar version: 0.3.1
- Laravel Version: 8.1.17
- PHP Version: #.#.#
- Database Driver & Version:

**Comment by glennjacobs** [comment]
Sounds like the Livewire assets are not loading. Please check the browser console. This is a common Livewire issue.

**Comment by parthagorai** [comment]
Please help me to fix

**Comment by glennjacobs** [comment]
Community support is available in Discord or you could Google it, plenty of results.

**Comment by LeftPinkie** [comment]
Not sure what is happening, but I had the same problem and when I went to refresh my admin login page and re-login... I was successful. If it happens again I will try to capture the logs and determine if there is a fix / work-around.
