### ISSUE TITLE
Lunar\Hub\AdminHubServiceProvider::Lunar\Hub\{closure}(): Argument #1 ($user) must be of type Lunar\Hub\Models\Staff

### ISSUE THREAD

**Issue by ryanmitchell** [lunarphp/lunar#1129]
- Lunar version: 0.3.1

### Expected Behaviour:
The change made here is a breaking change:
https://github.com/lunarphp/lunar/commit/4c4e429abbe2781160a14c7086393fa42918dda6

By adding Staff $model to the Gate::after it has caused Statamic's control panel on our installs to no longer work (they error out). I'd imagine it also conflicts with other Gate::afters() from other packages.

Can you check if the request is inside the Lunar hub before applying the Gate?

**Comment by glennjacobs** [comment]
@alecritson do we need to add `Staff $user`? Probably not needed and can simply be removed.

**Comment by alecritson** [comment]
@ryanmitchell I've got a patch PR up, if this fixes the issue for you let us know and we'll get it released!

**Comment by ryanmitchell** [comment]
Yep that works - thanks!
