### ISSUE TITLE
Admin hub not change to dark mode

### ISSUE THREAD

**Issue by thienthanit04** [lunarphp/lunar#1141]
- Lunar version: 0.4
- Laravel Version: 10.x
- PHP Version: 8.2
- Database Driver & Version:

### Expected Behaviour:
Dark mode
### Actual Behaviour:
Not working
### Steps To Reproduce:
![image](https://github.com/lunarphp/lunar/assets/106950633/6be1dd76-b1ac-43a0-9098-8e03401b472e)

**Comment by glennjacobs** [comment]
Darkmode functionality was never completed, so this feature isn't released yet. 

It's also not likely to ever be released in this version of the admin hub, as our intentions are to move to Filament v3.
