### ISSUE TITLE
PopulateProductOptionLabelWithName fails when using Postgress

### ISSUE THREAD

**Issue by vasilGerginski** [lunarphp/lunar#1143]
- Lunar version: 0.4.0
- Laravel Version: v10.13.5
- PHP Version: 8.1.17
- Database Driver & Version: pgsql 

### Steps To Reproduce:
Just upgrade to 0.4.0 and run php artisan migrate:fresh --seed

Issue is due to 
protected function shouldRun()
{
    return ProductOption::where('label', '')->orWhereNull('label')->count() > 0;
}

You can't have '' value for json fields in postgres.. it should be 

return ProductOption::whereNull('label')->count() > 0;

**Comment by glennjacobs** [comment]
Thanks for reporting. This is a tricky one as MySQL and Postgres seem to use different ways to determine an empty JSON field. We may need to detect the database driver and adjust this query accordingly.

**Comment by vasilGerginski** [comment]
removing the `->where('label', '')` seems to work...

**Comment by denova99** [comment]
Will using `->whereJsonLength('label', 0)` work for both MySQL and Postgres work?

**Comment by glennjacobs** [comment]
We will need to make it work in Sqlite, MySQL and PostgreSQL.

I think we need a GitHub Action to test in both MySQL and PostgreSQL.

**Comment by glennjacobs** [comment]
I wonder if whereJsonLength could help
https://laravel.com/api/7.x/Illuminate/Database/Query/Builder.html#method_whereJsonLength

**Comment by glennjacobs** [comment]
> Will using `->whereJsonLength('label', 0)` work for both MySQL and Postgres?

OMG, just saw I missed your reply and then came up with the same thing! LOL
