### ISSUE TITLE
Unable to reuse current cart session.

### ISSUE THREAD

**Issue by shahnawazkadari** [lunarphp/lunar#1146]
- Lunar version: 0.4.0
- Laravel Version: 10.15.0
- PHP Version: 8.1.10
- Database Driver & Version:

### Expected Behaviour:
CartSession::current() can be used multiple time.

### Actual Behaviour:
I'm working on a local environment
When I add cartline to cart, All session data gets flushed. Unable to use the current cart again to add multiple items.

### Steps To Reproduce:
After fresh installation
Created CartController (will be used for api call)
Route /cart
in index method
I do
```
function index(Request $request){
        $cart = CartSession::current();
        $purchasable = ProductVariant::where('id', 1)->first();
        $cart->add($purchasable, 12);
} 
```
When I hit once it's working
when I hit again...

Getting error
**Attempt to read property "id" on null**

I found that session gets destroyed after calling $cart->add.

**Comment by glennjacobs** [comment]
You have not provided any steps to reproduce, so I'm closing. If you require support, please see Discord or the Discussions section.

**Comment by shahnawazkadari** [comment]
I have provided steps to reproduce...
Please check!

**Comment by glennjacobs** [comment]
Can you please provide the stack trace?

**Comment by glennjacobs** [comment]
OK, I've looked at this and your code is slightly wrong.

You need to use `CartSession::add($purchasable, $quantity);`. That will create a cart if one doesn't exist.

`$cart = CartSession::current();` will only return a cart object if one has been created, or the config `lunar.cart.auto_create` is set to `true`.

**Comment by shahnawazkadari** [comment]
I missed the mention that, I've already set **auto_create** to **true**.

In `config/cart.php`
Also cached `config:cache`

**Comment by glennjacobs** [comment]
Also, check you have set-up the correct tax zones, otherwise it might complain also.

And be careful with auto-create, as it can end up creating a new cart for all visitors, regardless of whether they add something or not.

**Comment by shahnawazkadari** [comment]
> Also, check you have set-up the correct tax zones, otherwise it might complain also.
> 
> And be careful with auto-create, as it can end up creating a new cart for all visitors, regardless of whether they add something or not. 

I'm calling the route /cart by ajax post, So it doesn't matter.

**Comment by shahnawazkadari** [comment]
> Also, check you have set-up the correct tax zones, otherwise it might complain also.
> 
> And be careful with auto-create, as it can end up creating a new cart for all visitors, regardless of whether they add something or not. 

**By setting up the correct tax zones fixed issue 😊**


Thanks 😊
