### ISSUE TITLE
ProductVariant getThumbnail method returns thumbnail for Product, not ProductVariant

### ISSUE THREAD

**Issue by kylekanderson** [lunarphp/lunar#1178]
- Lunar version: 0.4.0
- Laravel Version: 10.17.1
- PHP Version: 8.2.8
- Database Driver & Version: MySQL v8

### Expected Behaviour:
Calling the `getThumbnail` method on a Product Variant should return the primary thumbnail set for the Product Variant.

### Actual Behaviour:
Calling the `getThumbnail` method on a Product Variant return the primary thumbnail set for the Product Variant's Product.

### Steps To Reproduce:
1. Create a Product having multiple Product Variants
2. Set a different primary image for the various Product Variants
3. Call the `getThumbnail` method on a Product Variant with a different primary image than the Product
4. Observe the the Product's primary image is returned, not the Product Variant's image
5. This regression can also be seen on the Product page in the Hub, as the thumbnails for all of a Product's variants are set to the primary image of the Product, not the Product Variant

I believe this was introduced with this change: https://github.com/lunarphp/lunar/pull/1112/files#diff-96dafc8117ede45ef690b989677dbb8fde5c49b42db1087e98282b3701540678

As a temporary solution, I've created a macro on the ProductVariant model that implements the previous `getThumbnail` method (getting the thumbnail from the pivot model instead of via custom properties on the Media model).

I think the solution here is to either update the Hub code to match this change in the Core code (i.e. wire-up the Primary toggle on the Product Variant's Images to toggle the 'primary' property in the Media's custom properties to true/false, in addition to updating primary property on the media_product_variant pivot table).

**Comment by alecritson** [comment]
Thanks @kylekanderson Got a PR to hopefully fix this up!
