### ISSUE TITLE
Prices are not being deleted when deleting ProductVariants

### ISSUE THREAD

**Issue by sanneterpstra** [lunarphp/lunar#1190]
- Lunar version: 0.4.1
- Laravel Version: 10.10
- PHP Version: 8.2
- Database Driver & Version: MariaDB v10

### Expected Behaviour:
The corresponding pricing rows in the lunar_prices table should be deleted.

### Actual Behaviour:
The pricing rows are not being deleted and will stay put until you manually remove then from the database

### Steps To Reproduce:
Create a product and toggle the Variants option. Create the variants by selecting the product options for the variants and click "Use selected options" button.

Then either remove the variants individually or remove the all at once by toggling the variants option to off on the product page. Check the database lunar_prices table and you will see that the corresponding prices will be left in the database.

**Comment by obayesshelton** [comment]
Hi,

I'm using Postgres and this is still an issue... not sure if anyone has mentioned this.
