### ISSUE TITLE
Shipping OrderLines Throws Error When Accessing Purchasable Relationship

### ISSUE THREAD

**Issue by kylekanderson** [lunarphp/lunar#1211]
- Lunar version: 0.5.0
- Laravel Version: 10.19.0
- PHP Version: 8.2.8
- Database Driver & Version: MySQL 8

### Expected Behaviour:
I should be able to access the `Lunar\DataTypes\ShippingOption` object through the `purchasable` relationship on an `OrderLine` object with a `purchasable_type` of `Lunar\DataTypes\ShippingOption`.

### Actual Behaviour:
When trying to access the `purchasable` relationship on an `OrderLine` object with a `purchasable_type` of `Lunar\DataTypes\ShippingOption` results in the following error:

> Too few arguments to function Lunar\DataTypes\ShippingOption::__construct(), 0 passed in /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php on line 793 and at least 5 expected

### Steps To Reproduce:

1. Ensure an `OrderLine` with a `purchasable_type` of `Lunar\DataTypes\ShippingOption` exists
2. Attempt to access the `purchasable` relationship on the `OrderLine` object (i.e. `$orderLine->purchasable`)
3. Observe the error above

With PR #1189, this is now breaking the Admin Hub Dashboard.

**Comment by kylekanderson** [comment]
I've submitted a PR with a failing unit test that replicates this issue.

**Comment by wychoong** [comment]
> I've submitted PR #1212 with a failing unit test that replicates this issue.

Would you able to add a failing test for the previous issue as well?

**Comment by RedionK** [comment]
This issue remains and needs to be reopened. While the fix takes care of the dashboard exception, it does not fix the actual bug. 

If the purchasable relationship of an orderLine that's a shipping option is accessed you will get the same error.
