### ISSUE TITLE
Fresh install "Class "NumberFormatter" not found"

### ISSUE THREAD

**Issue by shahidkarimi** [lunarphp/lunar#1224]
- Lunar version: latest
- Laravel Version: 9.52
- PHP Version: 8.1
- OS: Ubuntu 22.04
- Database Driver & Version: 

### Expected Behaviour:
Fresh install should working without any problem

### Actual Behaviour:
Class "NumberFormatter" not found

### Steps To Reproduce:
Just fresh installation

**Comment by wychoong** [comment]
Are you sure you are on the latest Lunar 0.5? The latest composer should flag the missing packages/dependencies
