### ISSUE TITLE
Asking to add USD price even when it's not the default and active

### ISSUE THREAD

**Issue by amitavroy** [lunarphp/lunar#1267]
- Lunar version: 0.6.0
- Laravel Version: 10.10
- PHP Version: 8.1.10
- Database Driver & Version: Mysql 8.0

### Expected Behaviour:
After creating a new current INR and enabling it, I disabled USD.
Then I try to create a product with the intention to add only INR price.

I was going through this issue #502 and the solution by Adam works however, it seems the latest version doesn't have this code. So, raising a PR

### Actual Behaviour:
I am still asked to add the USD price. The validation error doesn't allow me to save the product with just INR price.

### Steps To Reproduce:
1. Add new currency (INR in my case)
2. Enable the new current and make it default
3. Disable USD currency
4. Try to create product

![lunar_ss](https://github.com/lunarphp/lunar/assets/1438890/64b2d314-f80c-4d28-85e5-6ea63b322366)

**Comment by glennjacobs** [comment]
Disabling a currency is for the frontend. If you don't want to add prices, you will need to remove the currency.

**Comment by glennjacobs** [comment]
Solving this properly would require the system to delete all prices from products, orders etc. potentially a big task and highly risky, hence we don't offer a delete option currently. 

To solve the problem it would probably have to run as a background task and disable the hub whilst running. 

It's a lot of effort for a task that would rarely be used.

**Comment by glennjacobs** [comment]
I get that devs will want to change the currency on first install. Maybe there's a better way. But this isn't a bug as such, so an enhancement suggestion should be discussed in GitHub Discussions.
