### ISSUE TITLE
Hub product attributes not working

### ISSUE THREAD

**Issue by SteliyanPStoyanov** [lunarphp/lunar#1287]
In abstract class AbstractProduct 
   this is wrong  
 
```php
public function getAvailableAttributesProperty()
{
    return ProductType::find(
        $this->product->product_type_id
    )->productAttributes->sortBy('position')->values();
}
```

has to be like this to work

```php
 public function getAvailableAttributesProperty()
{
    return Attribute::whereAttributeType(Product::class)->orderBy('position')->get();
}
```

**Comment by alecritson** [comment]
@SteliyanPStoyanov Can you explain a bit more what issue you think this is causing and why your suggestion will fix it?

**Comment by glennjacobs** [comment]
That is not how attributes work with products. Product attributes are mapped via product types. Your suggestion is wrong.

**Comment by SteliyanPStoyanov** [comment]
in settings you have Attributes in type Product when you add new never show anyware and how have to fill this fields

**Comment by alecritson** [comment]
You need to make sure you associate them to the product type under `hub/product-types`

**Comment by SteliyanPStoyanov** [comment]
ok but why is type Product  not ProductType like Brand is Brand
