### ISSUE TITLE
Associations issue (HUB)

### ISSUE THREAD

**Issue by kallefrombosnia** [lunarphp/lunar#1289]
Hi, we have noticed when using associations on product (hub), when on the same page (without page refresh), it duplicates same entries again and again to the DB on save action.

- Lunar version: 0.6.0
- Laravel Version: 10.13.2
- PHP Version: 8.1
- Database Driver & Version: MySQL

### Expected Behaviour:
After choosing associations, hitting save product will only insert associations once.
### Actual Behaviour:
// 
### Steps To Reproduce:
1. Visit product page -> Associations 
2. Choose some associations here
3. Dont refresh the page!
4. Hit save product multiple times and you should see the issue after page reload or DB table.

After some debugging, it seems [$this->syncAssociations](https://github.com/lunarphp/lunar/blob/ecb29f17ad6cfa75cb622594fbbb4cd9da12342c/packages/admin/src/Http/Livewire/Components/Products/ProductShow.php#L25) is only called on component mount.
To fix this, I think it also should be called in the save action somewhere [here](https://github.com/lunarphp/lunar/blob/ecb29f17ad6cfa75cb622594fbbb4cd9da12342c/packages/admin/src/Http/Livewire/Components/Products/AbstractProduct.php#L505).

**Comment by alecritson** [comment]
Thanks @kallefrombosnia Got a PR for this fix, should be patched in the next minor release.

**Comment by alecritson** [comment]
This should be resolved in `0.6.2`, if the issue persists please reopen :)
