### ISSUE TITLE
Installing with MyISAM 

### ISSUE THREAD

**Issue by mackieee** [lunarphp/lunar#1295]
Hi! Downloaded Lunar to take a look and followed the docs. Hit a small snag on the installation which could be overcome with some minor detail in the documentation perhaps. 

- Lunar version: 0.6
- Laravel Version: 9.52
- PHP Version: 8.1
- Database Driver & Version: MySQL 8.0.31

### Expected Behaviour:

The migrate scripts complete upon issuing the  `php artisan migrate` command.

### Actual Behaviour:

![image](https://github.com/lunarphp/lunar/assets/883702/67b41aa4-dcad-49fb-9662-eaf8761f7784)

``` sql 
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`)) 
```

This is due a limitation hit with the MyISAM database engine - fix here was to set the default Database Engine to InnoDB.

``` SET GLOBAL default_storage_engine = 'InnoDB'; ```

Thereafter, recreate the DB and run the `php artisan migrate` again.

### Steps To Reproduce:

- Fresh Install from 0.6
- Prepare `.env` file & run `composer update`
- To reproduce the error, ensure the Database Engine is set to MyISAM. ( ```SET GLOBAL default_storage_engine = 'MyISAM';```)
- Run `php artisan migrate`

**Comment by alecritson** [comment]
Closing as it's apparently not a Lunar specific issue.
