### ISSUE TITLE
Issue with table builder $sortField

### ISSUE THREAD

**Issue by morawcik** [lunarphp/lunar#1298]
- Lunar version: 0.6.0+
- Laravel Version: 10.26+
- PHP Version: 8.1+

I tried find what needed to change to sort orders by created_at instead of placed_at and I see that there is an issue:
I changed $sortField to 'created_at' in OrdersTableBuilder class and nothing happened and in getData() $sortField returns 'placed_at'. 
I moved higher to OrdersTable and here (without any changes) in getData() $sortField returns null so it uses `$this->sortField ?: 'placed_at'` in return. 
Next i moved to HasSortableColumns trait (uses in Table - extended in OrdersTable) and after changed here $sortField to 'created_at' it works as should - orders are sorted by created_at field.

I guess that orderBy() in OrdersTableBuilder getData() can't override sort() from OrdersTable getData()

**Comment by wychoong** [comment]
@morawcik do you still need this?

**Comment by morawcik** [comment]
I totally forgot about this :D 
Not really - i'm already moved to 1.x and with tabs for each status I don't have to change placed_at to created_at :)

**Comment by morawcik** [comment]
@wychoong Btw I just saw - it would be nice to have in 1.x option to sort orders at least by date cuz now I see there is only by id ;)
