### ISSUE TITLE
baseColumns is ignored

### ISSUE THREAD

**Issue by m33ts4k0z** [lunarphp/lunar#1328]
LunarPHP 0.7

Running the snippet below in AppServiceProvider for hub, results in the standard columns to be shown instead of only the one desired.

```
public function boot(CustomersTableBuilder $customerTableBuilder)
{
    $customerTableBuilder->baseColumns(
        ['company_name']
    );
}
```

### Expected Behaviour:
Only the selected base columns will show.

**Comment by alecritson** [comment]
This is no longer an issue in 1.x
