### ISSUE TITLE
 Undefined property: stdClass::$currency_code at TaxBreakdown.php after upgrade from 0.6.* to 0.7.2

### ISSUE THREAD

**Issue by morawcik** [lunarphp/lunar#1340]
I can't see new orders in hub (orders created after upgrade)
Like in title:
 Undefined property: stdClass::$currency_code at /home/forge/papertino.art/vendor/lunarphp/lunar/packages/core/src/Base/Casts/TaxBreakdown.php:3

![Zrzut ekranu 2023-11-23 o 19 59 54](https://github.com/lunarphp/lunar/assets/4557530/a436556b-e1a1-4b90-9436-c64dce07b9cb)
first 3 rows are from newest orders (after upgrade).

**Comment by morawcik** [comment]
Ok, after while it seems like it's not related to this column. Now only second and last works ok

**Comment by morawcik** [comment]
The problem was in lunar_order_lines where my orders/lines for the "middle" orders was without"currency_code" and there was "total" not "value"

**Comment by alecritson** [comment]
Yeah that sounds like the old format, when you upgraded locally to test did you encounter any issues when running migrations? There is a state update that runs which should convert the orders and lines

**Comment by morawcik** [comment]
No, migrations ran without any problem or notifications - just standard migrations.

**Comment by alecritson** [comment]
There are state updates that happen after the migrations fire. It looks like for some reason this hasn't run on the order lines. A couple of things...

1. How many order lines do you have in the DB?
2. Are all order lines affected? (excluding new lines) i.e. does it look like some have been updated?
3. Can you provide the `tax_breakdown` content for some that haven't been converted? Ideally pasted in not screenshot.

**Comment by cambad** [comment]
Hey, got the same issue after I ran the migrations, then I ran the `php artisan optimize:clear` command and everything was good, the error was inside a cached view. 

I hope this solves your problem! 

Cheers

**Comment by morawcik** [comment]
[{"description":"VAT","total":368,"percentage":23}]

I tested it with older database and all 131 orders have updated tax breakdown (after migration) but for 42 of them order lines are not updated (206 order lines from 706)

@cambad not working for me

**Comment by alecritson** [comment]
So if you run migrations again does that number shrink? Trying to see if it's timing out or if there is something else at play not updating the order lines

**Comment by morawcik** [comment]
It does - now all are updated (even if this second time there was no migrations)

**Comment by alecritson** [comment]
Yeah the state updates run on migration events, so they still trigger even if there are none.

We've spoke about this internally and eventually would like an update command instead
