### ISSUE TITLE
Wrong tax value

### ISSUE THREAD

**Issue by morawcik** [lunarphp/lunar#1341]
- Lunar version: 0.7.2
- Laravel Version: 10
- PHP Version: 8.2

There is an problem with tax value - for e.g i have product which cost 12.00 PLN (6.00 PLN after discount)
stored_inclusive_of_tax = true
tax percentage - 23%
and i'm getting tax value: 112 when it should be 138

I see that in SystemTaxDriver there is:
```
$totalTaxPercentage = $taxAmounts->sum('percentage') / 100; // E.g. 0.2 for 20%
$priceExTax = round($subTotal / (1 + $totalTaxPercentage));
```
but second line should be:
```
$priceExTax = round($subTotal - ($subTotal * $totalTaxPercentage));
```

**Comment by netzknecht** [comment]
> `$priceExTax = round($subTotal / (1 + $totalTaxPercentage));`
The calculation of the amount without tax is definitely correct, the cause of the error must be found somewhere else.

**Comment by glennjacobs** [comment]
If you have 600 inclusive of tax and the rate is 23%, then to remove the tax you would do 

600 / 1.23 = 487.80

I don't see how you get to 462?

**Comment by ZebTheWizard** [comment]
These are equivalent when increasing by a percentage
```
x * 1.25 == x + (x * 0.25)
```

however, the following are not equal when decreasing by a percentage
```
x / 1.25 != x - (x * 0.25)
```


here's why
``` 
x / 1.25 
= x * 1 / 1.25  
= x * 0.8
```

and on the other side
```
x - (x * 0.25) 
= x * (1 - 0.25) 
= x * 0.75
```

depending on which calculation you use there will be a difference of 
```
p * p * x  / (p + 1)
```
