### ISSUE TITLE
Order loading error when having a transaction with more than 1 payment intent

### ISSUE THREAD

**Issue by dan-pascu** [lunarphp/lunar#1352]
- Lunar version: 0.7.2
- Laravel Version: 10.34.2
- PHP Version: 8.2.13
- Database Driver & Version: MariaDB 11.1.3

### Expected Behaviour:
When having a payment with more than one payment intent, to be able to display the order.

### Actual Behaviour:
When loading the orders, on line 64 in OrderCapture.php is checking for number of intents. If there is more than 1 intent, then the transaction is null and the capture.blade.php throws an error at line 26 `@if($this->transactionModel->amount->decimal > $amount)`

### Steps To Reproduce:

For a completed order add at least one more intent field:
<img width="901" alt="image" src="https://github.com/lunarphp/lunar/assets/8133463/cb2d8d86-5b4f-49fc-812d-15facaa9d745">

**Comment by alecritson** [comment]
This should no longer be an issue on v1
