### ISSUE TITLE
[HUB] Error when searching via Scout in LunarPHP HUB

### ISSUE THREAD

**Issue by Globalaj** [lunarphp/lunar#1355]
* Lunar version: 0.7.0
* Laravel Version: 10
* PHP Version: 8.2
* Database Driver & Version: 10.4.27-MariaDB

### Expected Behaviour:

When using LunarPHP Scout, make it possible to search for email, phone number with special characters like @ and + in the area code and more.

### Actual Behaviour:

When I search via HUB for an email address with a special @ sign or a phone number with a prefix with a special + sign, the following error pops up.

![image](https://uploads.linear.app/349e9a44-b829-4968-91b5-53f939b10c03/d2e63ba8-e1ad-4920-8644-86c7bb5bab73/717da213-2a8d-4837-a42e-b76aa2e879da?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM0OWU5YTQ0LWI4MjktNDk2OC05MWI1LTUzZjkzOWIxMGMwMy9kMmU2M2JhOC1lMWFkLTQ5MjAtODY0NC04NmM3YmI1YmFiNzMvNzE3ZGEyMTMtMmE4ZC00ODM3LWE0MmUtYjc2YWEyZTg3OWRhIiwiaWF0IjoxNzE3NDE4NzA5LCJleHAiOjMzMjg3OTc4NzA5fQ.zExEym2gNgeu10EZV0_Og-tDXVdQat_rZmqcYoNJ3tM)

**Comment by lguichard** [comment]
I submit a pull request, the exception due to query SQL on scout-database-engine

**Comment by wychoong** [comment]
there is a merged PR, that should closed this issue
