### ISSUE TITLE
ProductOptionValue model - getNameAttribute type error

### ISSUE THREAD

**Issue by bricehartmann** [lunarphp/lunar#1356]
- Lunar version: 0.7.2
- Laravel Version: 10.35
- PHP Version: 8.3
- Database Driver & Version: MySQL 8.0

### Expected Behaviour:
Creating a new `ProductOptionValue` or editing a `ProductOptionValue` from within the HUB settings successfully saves the new/modified `ProductOptionValue`.

### Actual Behaviour:
A type error is thrown when opening new/edit dialog:
```
Lunar\Models\ProductOptionValue::getNameAttribute(): Argument #1 ($value) must be of type string, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 658
```

### Steps To Reproduce:
1. From within the HUB, navigate to `Settings -> Product Options`
2. Use the kebab menu next to an existing `ProductOption` to select `Edit option`
3. Click the `Create option value` button

### Notes
With the accessor signature on the `ProductOptionValue` value being type-hinted as `string`:
```php
public function getNameAttribute(string $value) {...}
```
this type error occurs when the `name` property is accessed but there's no JSON string under the `name` attribute.

**Comment by obayesshelton** [comment]
Also, seeing this error

**Comment by obayesshelton** [comment]
I noticed I could create the option as per the docs. So maybe a short term work around is to make it in Tinker.

**Comment by lguichard** [comment]
The error happen after merge this commit : https://github.com/lunarphp/lunar/commit/c456c783cde72cb58ea6e588e864883da7b0db4e

Livewire trigger a null value on name attribute form.

You can fixed temporaly with change getNameAttribute method in ProductOption class

```php
class ProductOption extends BaseModel implements SpatieHasMedia
...
 public function getNameAttribute(string $value = null): mixed
    {
        return json_decode($value);
    }
``` 

You can also change in ProductOptionValue class : 

```php
class ProductOptionValue extends BaseModel implements SpatieHasMedia
...
    public function getNameAttribute(string $value = null): mixed
    {
        return json_decode($value);
    }
``` 

It's an abnormal behaviour that component OptionsIndex call name attribute with null value. I think will be fixed on the new Filament admin panel.
