### ISSUE TITLE
Installation error while using laravel/jetstream require livewire/livewire ^2.0 it conflicts with composer.json require (^3.0).

### ISSUE THREAD

**Issue by reza-kharestani** [lunarphp/lunar#1358]
- Lunar version: 0.7.2
- Laravel Version: ^10.10
- PHP Version: 8.2.13
- Database Driver & Version:

### Expected Behaviour:
To be able to install Lunar with Laravel 10 when laravel/jetstream is installed

### Actual Behaviour:
This error in the process of Installation:

    - lunarphp/lunar[0.1.0, ..., 0.1.6] require doctrine/dbal 3.3.7 -> found doctrine/dbal[3.3.7] but the package is fixed to 3.7.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - lunarphp/lunar[0.2.0, ..., 0.2.7] require laravel/framework ^8.0|^9.0 -> found laravel/framework[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^10.10).
    - lunarphp/lunar[0.3.0, ..., 0.7.2] require livewire/livewire ^2.0 -> found livewire/livewire[v2.0.0, ..., v2.12.6] but it conflicts with your root composer.json require (^3.0).
    - Root composer.json requires lunarphp/lunar * -> satisfiable by lunarphp/lunar[0.1.0, ..., 0.7.2].

### Steps To Reproduce:
1. Insatll Laravel 10
2. Install Laravel Jetstream
3. Try to install Lunar

### Suggestion:
I am not that familiar with the differences between Livewire version 2 and 3 but Maybe it will be possible to change the composer file to simply: 
    "livewire/livewire": "^2.0|^3.0",

**Comment by glennjacobs** [comment]
You may install Lunar's core without compatibility issues, but the admin hub is not compatible with Livewire v3. The Filament admin panel will address that when released.

**Comment by reza-kharestani** [comment]
Thanks
