### ISSUE TITLE
Update tests to use PHP 8.3

### ISSUE THREAD

**Issue by glennjacobs** [lunarphp/lunar#1387]

**Comment by Wennlys** [comment]
All tests are passing when using PHP 8.3.
![image](https://github.com/lunarphp/lunar/assets/49328570/a1ebdb6f-28f7-4827-aeb2-a646cb630ee1)

**Comment by glennjacobs** [comment]
> All tests are passing when using PHP 8.3. ![image](https://private-user-images.githubusercontent.com/49328570/292920471-a1ebdb6f-28f7-4827-aeb2-a646cb630ee1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MzEzODEsIm5iZiI6MTcwMzYzMTA4MSwicGF0aCI6Ii80OTMyODU3MC8yOTI5MjA0NzEtYTFlYmRiNmYtMjhmNy00ODI3LWFlYjItYTY0NmNiNjMwZWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDIyNTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NGU2NjkyZTMxOTZkNDBkOGJkNjhkOTU1NzEwNTM5ZjRkMWUzZGEyYzYwMGRjYzAzZGQ2YzMxNDQ1NDk2NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rRuVLqxetQdOeA8Ock2GPzD5Wgmd-pziNOBL3ShZQto)

Thanks for confirming. This issue is mainly about updating the GitHub Action workflows so they test against 8.3 and probably remove 8.1, which I guess will align with Laravel 11 when it's released.
