### ISSUE TITLE
Reintroduce the installation command for the admin panel

### ISSUE THREAD

**Issue by glennjacobs** [lunarphp/lunar#1417]
Currently, there is no option to create a Staff login when installing `v1.0`.

The install command from the previous hub needs to be implemented. See https://github.com/lunarphp/lunar/blob/0.7/packages/admin/src/Console/Commands/InstallHub.php

We don't have any custom assets to be publishing this time, but we might want to incorporate publishing Filament's assets perhaps?

**Comment by lguichard** [comment]
Yes add command filament:assets prevent that the user forgetting information on the documentation.
