### ISSUE TITLE
When a product does not have a translated name in the current language, there is no link to click on in the products table.

### ISSUE THREAD

**Issue by tdwesten** [lunarphp/lunar#1439]
When a product does not have a translated name in the current language, there is no link to click on in the products table.

<img width="1709" alt="Scherm­afbeelding 2024-01-02 om 12 10 59" src="https://github.com/lunarphp/lunar/assets/224501/afc1a942-38b8-415a-97f3-e08ba88fe105">

- Lunar version: 0.7.4
- Laravel Version: v10.39.0
- PHP Version:8.2.13
- Database Driver & Version: MYSQL 8

### Expected Behaviour:
When a product does not have a translated name in the current language, show the SKU.

### Actual Behaviour:
There is nothing shown.

### Steps To Reproduce:
1. Create a new product.
2. Only add the product name for non-default languages.
3. Check the products table.

**Comment by joalea** [comment]
Can confirm this.

**Comment by aizensoosuke** [comment]
Related to #1735?
