### ISSUE TITLE
Cannot create root collection

### ISSUE THREAD

**Issue by morawcik** [lunarphp/lunar#1538]
- Lunar version: 1.x
- Laravel Version: 10.x (latest version)
- PHP Version: 8.2

Steps:
On fresh install go to collections
create new collection group
enter to this group
create root collection and after clicking "create":

> Attempt to read property "type" on null

![image](https://github.com/lunarphp/lunar/assets/4557530/b525146d-717e-4909-b0f4-fa11eba29fe5)

**Comment by lguichard** [comment]
Are you sure to have Name and Description fields on Attribute Group type "Lunar\Models\Collection". 

![Capture d’écran 2024-02-07 à 14 58 40](https://github.com/lunarphp/lunar/assets/6489718/e75a54bb-fef8-49b6-bb0e-0108546a3ad2)


The 1.x branch is under development, the install command isn't stable.

**Comment by morawcik** [comment]
Yeah, install needs a lot of work. It doesn't add any data because import countries command is finished with exit which terminates next actions...

**Comment by lguichard** [comment]
A PR is open https://github.com/lunarphp/lunar/pull/1419

**Comment by alecritson** [comment]
Closing since this is quite an old issue at this point, the panel has come a fair way and doesn't seem to be relevant anymore.
