### ISSUE TITLE
Taxes Are Applied When Marked As Inactive

### ISSUE THREAD

**Issue by dewebdesigns** [lunarphp/lunar#1547]
- Lunar version: 0.8.0
- Laravel Version: 10.43.0
- PHP Version: 8.3.2
- Database Driver & Version: MariaDB 11.1.2 

### Expected Behaviour:

When you have multiple tax zones, in my instance, postcodes, and mark one as inactive, it should not return the inactive tax zone.

### Actual Behaviour:

It returns the first tax zone that matches whether it is active or inactive, and sets the tax even if it is inactive.

There are no checks for the `active` column on the tax zone for any of the queries in the file: `core/src/Actions/Taxes/GetTaxZone.php`

### Steps To Reproduce:

Create a tax class.
Create a tax zone with the tax rate to 10% and set it as inactive.
Add a product to your cart, set an address, and check the tax on the product. It will be at 10%.

This works for tax countries, tax states, and tax post codes. 

The only way I can disable the taxes in my production site is to delete any matching records, which is not ideal.

**Comment by alecritson** [comment]
Relates to #1624 which has an open PR to fix.
