### ISSUE TITLE
Unable to install lunarphp/core 1.x-dev standalone

### ISSUE THREAD

**Issue by Wemalix** [lunarphp/lunar#1591]
Hello, I am trying to install the core package 1.x-dev, standalone to separate the storefront from the admin area. I'm facing the issue described bellow 

- Lunar version: 1.x-dev
- Laravel Version: 10.46.0
- PHP Version: 8.3.0
- Database Driver & Version: MySQL8

### Expected Behaviour:
Ability to install lunarphp/core standalone without the admin package

### Actual Behaviour:
When running `composer require lunarphp/core:1.x-dev -W` it is looking for _lunarphp/scout-database-engine_ which has been deleted (according to a discussion on Discord)
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires lunarphp/core 1.x-dev -> satisfiable by lunarphp/core[1.x-dev].
    - lunarphp/core 1.x-dev requires lunarphp/scout-database-engine 1.x-dev -> found lunarphp/scout-database-engine[dev-main, dev-0.7_0.8_branch_merge, 0.1.0-rc.1, ..., 0.x-dev] but it does not match the constraint.
```
    
### Steps To Reproduce:
Fresh Laravel install, then run : `composer require lunarphp/core:1.x-dev -W`

Thanks for your help

**Comment by ouail** [comment]
I faced the same issue, 
As a temporary fix, you could add this to your composer.json

```
"replace": {
    "lunarphp/scout-database-engine": "*"
}
```

**Comment by adevade** [comment]
This issue can be closed, I believe?
