### ISSUE TITLE
Get error when trying to edit product option in 2nd language

### ISSUE THREAD

**Issue by cleargoal** [lunarphp/lunar#1613]
- Lunar version: 0.8
- Laravel Version: 9.52.16
- PHP Version: 8.3.3-1
- Database Driver & Version: pgsql,  ver. 15

### Expected Behaviour:
Edit the Ukrainian option's name (or any other) language, save it, and use it without errors.

### Actual Behaviour:
When I started to write a value into the proper field - please see the screenshot
![Screenshot from 2024-03-06 21-56-43](https://github.com/lunarphp/lunar/assets/10929782/1094aad5-1771-4be9-8a31-f15f1cbb4d63)
just after 2nd letter the form gets submitted and produces the error 

> Lunar\Models\ProductOption::Lunar\Models\{closure}(): Argument #1 ($value) must be of type string, null given

### Steps To Reproduce:
All steps are made in the **admin 'Settings' area**.

1. add new language, don't set it as default. In my case, it's Ukranian' with the original name "Українська" and with the code 'uk'.
2. click Options under the topic 'Product' and then for the 'Size' option choose the right context menu, where choose 'Edit Option'.
3. For the field 'Name' click the button 'Locales' then you'll see all locales you created with the field, as you see on my screenshot.
4. print localized option name. In my case, it's 'розмір' but I can't add more than 2 letters.

**Comment by alecritson** [comment]
This will be fixed in 1.0.0-alpha.37

**Comment by cleargoal** [comment]
> This will be fixed in 1.0.0-alpha.37

OK
