### ISSUE TITLE
Customer Group Pricing not displayed for minimum quantity is 1

### ISSUE THREAD

**Issue by ouail** [lunarphp/lunar#1614]
- Lunar version: 1.x-dev
- Laravel Version: 10.46.0
- PHP Version: 8.3
- Database Driver & Version: mySQL8

Hello,

On the admin panel, I have set up Customer groups and pricing for those groups with no minimum quantity.

### Expected Behaviour:
Customer group pricing should be shown even if the quantity is set to 1.

### Actual Behaviour:
The pricing is not displayed when the min_quantity is set to 1.

I have identified that the "Price breaks" table only appears if customer group pricing has tier pricing.

You can find more details in the code at [#Support/RelationManagers/PriceRelationManager.php](https://github.com/lunarphp/lunar/blob/2298d629119b22e8a4332c0005efb522f5201320/packages/admin/src/Support/RelationManagers/PriceRelationManager.php#L99)

### Steps To Reproduce:
Create a random customer group.
Add pricing for that group and set the minimum quantity to 1.

Thanks

**Comment by glennjacobs** [comment]
Yes, we are aware of this issue. I believe @wychoong is going to work on a solution.

**Comment by ouail** [comment]
> Yes, we are aware of this issue. I believe @wychoong is going to work on a solution.

We have discussed this on Discord. Glad to hear it's on track and being worked on. Thank you

**Comment by ryanmitchell** [comment]
This was included in alpha7 so I think this can be closed
