### ISSUE TITLE
Error when associate products

### ISSUE THREAD

**Issue by joaoppcastro** [lunarphp/lunar#1650]
- Lunar version: 1.x-alpha6.
- Laravel Version: 10.48.2
- PHP Version: 8.1
- Database Driver & Version: PostgreSQL

### Expected Behaviour:
In the products tab, we should be able to associate products in the last tab of the menu on the right.
### Actual Behaviour:
https://flareapp.io/share/qm1Z2xRP
### Steps To Reproduce:
Menu Products last tab in right side, have a product association and when I click to search for the product the error appears.

**Comment by ryanmitchell** [comment]
Looks like you have a product that doesnt have a 'type' associated with it. Type should be required.

**Comment by alecritson** [comment]
Closing as this doesn't appear to be an issue with the Lunar panel, but more an issue with data.
