### ISSUE TITLE
Error when saving a product with a `Lunar\FrieldTypes\TranslatedText` attribute

### ISSUE THREAD

**Issue by MedRochonTolle** [lunarphp/lunar#1655]
- Lunar version: 1.0.0-alpha.7
- Laravel Version: 10.48.3
- PHP Version: 8.1.27
- Database Driver & Version: MySql 8

### Expected Behaviour:
Save your product and the data is saved

### Actual Behaviour:
When you save the product you get an error

### Steps To Reproduce:
Add an Attribute Group with an attribute of type `Lunar\FrieldTypes\TranslatedText` to a product type.

Try to save the product.

You get the error

`Lunar\FieldTypes\TranslatedText value must be a collection.`

### Additional info:

I think the error occurs since this fix but I'm not sure: https://github.com/lunarphp/lunar/pull/1639

Looks like I'm not able to save the description field either, but there's no error.

![image](https://github.com/lunarphp/lunar/assets/145382190/58e30bcd-815f-440f-8373-6e3683794c98)

**Comment by lguichard** [comment]
Thanks for your feedback. It appears after recents changes on this commit https://github.com/lunarphp/lunar/commit/172f595b7e0582950f2f015c6a8e1db4c054d48

@ryanmitchell do you have an idea ?

I’ll review my code about TranslatedText

**Comment by ryanmitchell** [comment]
I don't see this error in alpha7 - saving works fine for me on translated fields.

**Comment by jerwinaton** [comment]
Same issue here,

- Lunar version: 1.0.0-alpha.7
- Laravel Version: 10.43
- PHP Version: 8.2
- Database Driver & Version: MySql 8

Mine was when after creating a new product, and then update the **brand** or **description**.

You get the error

`Lunar\FieldTypes\TranslatedText value must be a collection.`

**Comment by wch-andrzej-k** [comment]
I have the same issue that occurs when I try to update the basic product data.

`Lunar version: 1.0.0-alpha.7`

**Comment by olivierguerriat** [comment]
I have a similar error with `ListField` on `1.0.0-alpha.8` (after further testing, it appears to be introduced by `1.0.0-alpha.6`):
```
Lunar\FieldTypes\ListField value must be an array.
```
when saving a product variant's "basic information" page.

**Comment by olivierguerriat** [comment]
For ListField, 172f595 appears to override the `dehydrateStateUsing` function used in [Support/FieldTypes/ListField.php](https://github.com/lunarphp/lunar/blob/172f595b7e0582950f2f015c6a8e1db4c054d48b/packages/admin/src/Support/FieldTypes/ListField.php).

But [TranslatedText](https://github.com/lunarphp/lunar/blob/172f595b7e0582950f2f015c6a8e1db4c054d48b/packages/admin/src/Support/FieldTypes/TranslatedText.php) doesn't use `dehydrateStateUsing` itself.

**Comment by bangnokia** [comment]
I can confirm I got that too, when editting product and collection

**Comment by alecritson** [comment]
I'm fairly certain (correct me if i'm wrong) but this is as a result of changing the type of the attribute after you have a product created. So it's not updated the `attribute_data` to be in the new format and so if you're going from `TranslatedText` to `Text` you will see `[Object, Object]` in the input field, but going from `Text` to `TranslatedText` you will get the error above? 🤔

**Comment by wychoong** [comment]
@MedRochonTolle @olivierguerriat @bangnokia @wch-andrzej-k is this still an issue after updating to the latest release?

**Comment by bangnokia** [comment]
thank @wychoong, it fixed for me
