### ISSUE TITLE
Error when attaching `discount` to a `customerGroup` in the Admin Hub

### ISSUE THREAD

**Issue by ha-zeek** [lunarphp/lunar#1657]
- Lunar version: 1.0.0-alpha.7
- Laravel Version: 10.48.3
- PHP Version: 8.1
- Database Driver & Version: MySQL 8.2

### Expected Behaviour:
The `Discount` should be attached to a `CustomerGroup` .

### Actual Behaviour:
an error is prompted (refer image). 

![image](https://github.com/lunarphp/lunar/assets/108339521/5c4dd0a1-d556-4979-8040-e8a487ecf93d)

There is the `customerGroups` relationship in the `Lunar\Models\Discount`, however it is calling the relationship from `Lunar\Models\CustomerGroup` instead.

### Steps To Reproduce:
In Admin Hub, create a discount and attach it to a customerGroup.

**Comment by ryanmitchell** [comment]
A similar error happens with scheduling channel availability

**Comment by ryanmitchell** [comment]
Can be closed now https://github.com/lunarphp/lunar/pull/1658 has merged
