### ISSUE TITLE
Lunarphp 1.x is not working with Model::shouldBeStrict(); because of dynamic attributes

### ISSUE THREAD

**Issue by AidasK** [lunarphp/lunar#1693]
- Lunar version: v1.0.0-alpha.9
- Laravel Version: v11
- PHP Version: 8.2

### Expected Behaviour:

Lunarphp should work fine with `Model::shouldBeStrict(); `. Strict mode forces developers to use good practices which helps to avoid poorly written code which leads to unexpected issues later on.

### Actual Behaviour:
Lunar crashes with `The attribute [morphClass] either does not exist or was not retrieved for model [Lunar\Models\TaxClass].` message.

### Steps To Reproduce:
1) Add Model::shouldBeStrict();  to app service providers boot method.
2) Try to edit tax class or any other resource at lunar http://localhost/lunar/tax-classes/1/edit

**Comment by alecritson** [comment]
`shouldBeStrict` doesn't cause this issue for me. Judging by the error message it looks like it can't find the polymorphic class that is referenced.  Going on a bit of a guess here, but have you used the model extending PR branch? Since currently polymorphic relations use the full class reference.

**Comment by AidasK** [comment]
I guess this new PR fixes stuff. You did such a great job with it, keep on rolling! I will close this for now and wait for pr to be merged.
