### ISSUE TITLE
Lunar 1.0: SQL Migration error when running migrations for the first time.

### ISSUE THREAD

**Issue by Timtendo12** [lunarphp/lunar#1698]
- Lunar version: 1.0.0-alpha.9
- Laravel Version: 11
- PHP Version: 8.3.4
- Database Driver & Version: MariaDB 10.4.28

### Expected Behaviour:
Running all migrations without errors.

### Actual Behaviour:

I get an error when running migrations on the following table:

`2022_01_18_100000_add_starts_ends_at_to_channelables_table`

error:
```
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'starts_at' (Connection: mysql, SQL: alter table `lunar_channelables` change `published_at` `starts_at` datetime null default 'NULL'
```

### Steps To Reproduce:

1. Start a fresh laravel project
2. Install lunar `composer require lunarphp/lunar:"^1.0.0-alpha" -W`
3.  run migrations `php artisan migrate`

**Comment by Timtendo12** [comment]
Potentional fix could be changing the migration to:

```php
    public function up()
    {
        /**
         * SQLite will only allow one per transaction when modifying columns.
         */
        Schema::table($this->prefix.'channelables', function (Blueprint $table) {
           $table->renameColumn('published_at', 'starts_at')->nullable()->change();
           $table->index('starts_at');
        });

        Schema::table($this->prefix.'channelables', function (Blueprint $table) {
            $table->dateTime('ends_at')->after('starts_at')->nullable()->index();
        });
    }
```

**Comment by alecritson** [comment]
Strange one, I've not come against this and we do have a test case which should run migrations and then rollback to ensure this kind of thing works. If you think this is a fix then happy to see a PR and we can take a look :)

**Comment by wch-kamil** [comment]
<img width="1890" height="576" alt="Image" src="https://github.com/user-attachments/assets/d8329c9d-cc3f-40de-baa4-ec6223354618" />

Do wyjaśnienia wrzucam
