### ISSUE TITLE
Attribute validation rules

### ISSUE THREAD

**Issue by ThorNissen** [lunarphp/lunar#1712]
* Lunar version: `^1.0.0-alpha`
* Laravel Version: `^11.0`
* PHP Version: `^8.2`
* Database Driver & Version: Using Laravel Sail image `mysql/mysql-server:8.0`

### Expected Behaviour:

In `0.8` it was possible to add a validation rule to an attribute.
The same should be possbile in `1.0.0-alpha`

### Actual Behaviour:

Right now it doesn't use the rule when using the attribute.

### Steps To Reproduce:

* A fresh Lunar `1.0.0-alpha` installation.
* Create an attribute group eg. "SEO".
* Create an attribute on the group eg. "Meta description" with the rule `max:50`
* Use the attribute on a product and save the product. (Should validate using `max:50` but it doesn't)

Example of `1.0.0-alpha` rule setup

![1 0-rules](https://uploads.linear.app/349e9a44-b829-4968-91b5-53f939b10c03/70c675cb-0f53-48d9-9786-2d60b795c8da/c5bd0045-c272-4b5c-ad0c-ee9d2f969070?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM0OWU5YTQ0LWI4MjktNDk2OC05MWI1LTUzZjkzOWIxMGMwMy83MGM2NzVjYi0wZjUzLTQ4ZDktOTc4Ni0yZDYwYjc5NWM4ZGEvYzViZDAwNDUtYzI3Mi00YjVjLWFkMGMtZWU5ZDJmOTY5MDcwIiwiaWF0IjoxNzE2MjcyNzkwLCJleHAiOjMzMjg2ODMyNzkwfQ.9dEsnyvLjkQAsGbUwT1I0bsqMuxjHe_mcnMmqsTqf8Q)

Example of `0.8` rule setup

![0 8-rules](https://uploads.linear.app/349e9a44-b829-4968-91b5-53f939b10c03/76c1952f-49cd-4cbc-8145-25058ae8ad32/677aedb3-dbe4-4a0e-9163-5c4f57b89c7a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM0OWU5YTQ0LWI4MjktNDk2OC05MWI1LTUzZjkzOWIxMGMwMy83NmMxOTUyZi00OWNkLTRjYmMtODE0NS0yNTA1OGFlOGFkMzIvNjc3YWVkYjMtZGJlNC00YTBlLTkxNjMtNWM0ZjU3Yjg5YzdhIiwiaWF0IjoxNzE2MjcyNzkwLCJleHAiOjMzMjg2ODMyNzkwfQ.8_LJvI3WAqntelRzu7zF_-IT51dZKDxkEuIhs5JYuDw)

Example of `0.8` validation

![0 8-validation](https://uploads.linear.app/349e9a44-b829-4968-91b5-53f939b10c03/6adde021-b6f5-48bb-8876-8c8ae968736f/dd3268c8-45c7-49e8-bb33-9b88fc61852a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM0OWU5YTQ0LWI4MjktNDk2OC05MWI1LTUzZjkzOWIxMGMwMy82YWRkZTAyMS1iNmY1LTQ4YmItODg3Ni04YzhhZTk2ODczNmYvZGQzMjY4YzgtNDVjNy00OWU4LWJiMzMtOWI4OGZjNjE4NTJhIiwiaWF0IjoxNzE2MjcyNzkwLCJleHAiOjMzMjg2ODMyNzkwfQ.O6GI2rguUme9ojVy1Ig1rEq5hsgOi9Q7vM4ybjw2NME)

**Comment by wychoong** [comment]
@ThorNissen does this https://github.com/lunarphp/lunar/pull/1798 fix for you?

**Comment by ThorNissen** [comment]
> @ThorNissen does this #1798 fix for you?

I'm currently not able to give it a test. 
But looking at the PR it seems to do the job 👍🏻
