### ISSUE TITLE
Url::scopeDefault() types `QueryBuilder` instead of `EloquentBuilder`

### ISSUE THREAD

**Issue by adevade** [lunarphp/lunar#1728]
* Lunar version: 1.0.0-alpha.17
* Laravel Version: 11.7.0
* PHP Version: 8.3.6
* Database Driver & Version: SQLite 3.45

### Expected Behaviour:

When calling `Url::default()->first()` I get an error because the wrong class is typed in the `scopeDefault()` method.

Switch `use Illuminate\Database\Query\Builder;` for `use Illuminate\Database\Eloquent\Builder;` in the use statements.

### Actual Behaviour:

```sh
> Lunar\Models\Url::default()->where('slug', 't-shirt')->first()
 
  TypeError Lunar\Models\Url::scopeDefault(): Argument #1 ($query) must be of type Illuminate\Database\Query\Builder, Illuminate\Database\Eloquent\Builder given, called in vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php on line 1631.
```

### Steps To Reproduce:

```php
\Lunar\Models\Url::default()->first();
```

**Comment by alecritson** [comment]
Thanks @adevade There's now a PR for this and should be done in the next release :)

**Comment by adevade** [comment]
Awesome! I was going to send a PR myself, but was just wrapping up for the day when i discovered the bug, so I just created an issue and then I forgot about it 🙈 

Thanks!
