### ISSUE TITLE
No label for Collection when using a second locale.

### ISSUE THREAD

**Issue by aizensoosuke** [lunarphp/lunar#1735]
- Lunar version: 1.0.0-alpha.17
- Laravel Version: 11.7.0
- PHP Version: 8.3.6
- Database Driver & Version: mysql  Ver 8.0.32 for Linux on x86_64 (MySQL Community Server - GPL)

### Expected Behaviour:
When a collection does not have a name in english, but has a name in another language, then that name should be shown. That is especially true if the other language is the default language.

### Actual Behaviour:
The collection has no label in the hub and is thus not editable.

### Steps To Reproduce:
- Fresh install of laravel (I use the sail version, `curl -s "https://laravel.build/project-name" | bash -`.
- Fresh install of lunarphp (setup the model, the panel, install meilisearch/meilisearch-php, run lunar:install)
- Go to the hub and create a second language (for example Français - fr). Set it as default.
- Go to collections, main collection, and create a root collection (for example, "Collection"). Do not click the "locales" button so that only a french label is created.
- The collection as no label, and is not editable

![image](https://github.com/lunarphp/lunar/assets/26968781/6e5ef743-fd73-44ea-876e-db6819bae1c2)

**Comment by alecritson** [comment]
This will be resolved in the next release
