### ISSUE TITLE
Undefined array key "email" when creating staff member

### ISSUE THREAD

**Issue by firebulb** [lunarphp/lunar#1741]
Thanks for all the hard work on lunar, just wanted to bring this issue to your attention. I've gone with 0.8 until v1 is ready.

- Lunar version: 0.8.1
- Laravel Version: 10.48.10
- PHP Version: 8.1
- Database Driver & Version: MySQL 8

### Expected Behaviour:

Display create staff member form.

### Actual Behaviour:

Display exception Undefined array key "email" when attempting to visit the create staff member form.

### Steps To Reproduce:

visit [url]/hub/settings/staff/create

**Comment by alecritson** [comment]
Thanks @firebulb as we move to v1 beta it's unlikely we'll hit hub issues, if you want to do a PR we'd review it otherwise we will close as this will be fixed in v1
