### ISSUE TITLE
Lunar 1.0 Admin Panel: Decimal places bug when creating Discount, in Minimum Cart Amount & Amount (Fixed Value)

### ISSUE THREAD

**Issue by ha-zeek** [lunarphp/lunar#1749]
- Lunar version: 1.0.0-alpha.17
- Laravel Version: 10.48.10
- PHP Version: 8.1
- Database Driver & Version: MySQL 8

### Expected Behaviour:

In `Discount Resource` in Admin Panel, adding 1 GBP instead 0.01 GBP to get £1.00 off or £1.00 minimum cart amount.

### Actual Behaviour:

![image](https://github.com/lunarphp/lunar/assets/108339521/33d8c30d-3f61-4469-bf47-1d20a3483ce2)

I'd have to put 0.01 GBP, to get £1.00.

![image](https://github.com/lunarphp/lunar/assets/108339521/cd157965-a796-4ba0-80a6-19aad510e173)

### Steps To Reproduce:

1. Create a currency with 2 decimal place as such

![image](https://github.com/lunarphp/lunar/assets/108339521/dfc9b0ae-2127-4225-9f9b-ff31f09b3bf2)

2. Create a discount in admin panel and fill in the minimum cart amount & amount off (fixed value).

**Comment by alecritson** [comment]
Thanks @ha-zeek Think I tracked it down and I've started a draft PR. Just need to double check tests and if anymore are needed them hopefully this will be fixed up.
