### ISSUE TITLE
Migrations for causer_type field in activity_log table

### ISSUE THREAD

**Issue by morawcik** [lunarphp/lunar#1759]
- Lunar version: 1.x
- Laravel Version: 11.x
- PHP Version: 8.2

Migrations from 0.8 to 1.x didn't change Lunar\Hub\Models\Staff to Lunar\Admin\Models\Staff in causer_type field in activity_log table

**Comment by alecritson** [comment]
Thanks @morawcik I've done a PR to update the upgrading docs. This will be  redundant once model extending has been QA'd and merged :)
