### ISSUE TITLE
Price break modal no longer opening after alpha.37 update

### ISSUE THREAD

**Issue by tominal** [lunarphp/lunar#1921]
I believe this may be related to a recent filament upgrade or something. I tried downgrading to alpha.36 and got the same result.

- Lunar version: 1.0.0-alpha.37
- Laravel Version: 10.48.20
- PHP Version: 8.2.22
- Database Driver & Version: MySQL 8.0.39

### Expected Behaviour:
Modal opens on click

### Actual Behaviour:
Frontend console error on modalContainer being undefined

![image](https://github.com/user-attachments/assets/8c6b12c8-548a-479c-a9f6-ecec4a15d007)

### Steps To Reproduce:
![image](https://github.com/user-attachments/assets/01f5d131-690f-4a75-807d-d168f8542937)

**Comment by glennjacobs** [comment]
Can you check if you're on the latest version of Filament? It should be v3.2.107

**Comment by tominal** [comment]
> Can you check if you're on the latest version of Filament? It should be v3.2.107

Yep! On 3.2.107

![image](https://github.com/user-attachments/assets/6034e809-12f8-4e6f-9bdf-d9416629c469)

**Comment by alecritson** [comment]
I have just tried to reproduce this without success, everything appears to work as intended. Can you try republishing the filament assets `php artisan filament:assets` ?

**Comment by tominal** [comment]
> I have just tried to reproduce this without success, everything appears to work as intended. Can you try republishing the filament assets `php artisan filament:assets` ?

I want to say that that fixed it! I am not 100% sure though because I ran `composer update` as well which brought filament to 3.2.108 and I don't see any files that were changed in the repo or public assets..
