### ISSUE TITLE
Cannot update `meta` of existing `OrderLine` instance

### ISSUE THREAD

**Issue by ken717w** [lunarphp/lunar#1942]
- Lunar version: 1.0.0-beta.1
- Laravel Version: 11.22.0
- PHP Version: 8.3.11
- Database Driver & Version: MySQL 8.0.32

### Expected Behaviour:

Successfully save the updated meta data to database.

### Actual Behaviour:

Gets error "class_implements(): Class product_variant does not exist and could not be loaded".

### Steps To Reproduce:

When creating the order line object, I followed the [docs](https://docs.lunarphp.io/core/reference/orders.html#order-lines) and set `purchasable_type` to `product_variant`.

```
$item = new OrderLine;
$item->purchasable_type = 'product_variant';
// ... Setting other attributes
$item->save();

// ... Do something else
$item->meta = [
  'key' => 'value',
]
$item->save();
```

Currently my workaround to make it works is to set `purchasable_type` to either `\Lunar\Models\ProductVariant::class` or `get_class($variant)`.

**Comment by nathanjansen** [comment]
Isn't this a duplicate or at least a relation of #1939 ?

**Comment by ken717w** [comment]
> Isn't this a duplicate or at least a relation of #1939 ?

I'm not 100% sure because in my case I've extended `Product` but not `ProductVariant` which could make a difference.

**Comment by nathanjansen** [comment]
> > Isn't this a duplicate or at least a relation of #1939 ?
> 
> I'm not 100% sure because in my case I've extended `Product` but not `ProductVariant` which could make a difference.

That makes sense because the 'default' (Laravel) way right now is the actual class name so in this case Lunar\Models\ProductVariant
I think if you take a look at your order_lines table this is the morph model added to the purchasable_type column. Not the 'product_variant'. If you use this github version: https://github.com/theimerj/lunar.git. It should be 'product_variant'. But check your database.

**Comment by repl6669** [comment]
Hey @ken717w, can you try by installing this version?

```php
"require": {
    "lunarphp/lunar": "dev-update-container-resolution as 1.0.0-beta.1",
},
"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/theimerj/lunar.git"
    }
]
```

That directly corelated to https://github.com/lunarphp/lunar/pull/1933 which will hopefully fix most of the problems with extending.

**Comment by ken717w** [comment]
@theimerj Thanks for the update. Your version works for me after I rollbacked the changes I mentioned [here](https://github.com/lunarphp/lunar/issues/1939#issuecomment-2337032656).

**Comment by ken717w** [comment]
#1949 doesn't seem to have fixed this issue. I can only get it to work by setting to `lunar_order_lines`.`purchasable_type` to `Lunar\Models\ProductVariant`.
