### ISSUE TITLE
Call to a member function getMorphClass() on string

### ISSUE THREAD

**Issue by devghor** [lunarphp/lunar#1953]
- Lunar version: 1.x
- Laravel Version: 11.x
- PHP Version: 8.2

### Expected Behaviour:
Collection can be attached with product
### Actual Behaviour:
![image](https://github.com/user-attachments/assets/a650dd6c-d7a1-4fb9-9ba1-832d2a5ddf11)

**Comment by luizsilva-dev** [comment]
The same here. Starter kit new installation.
