### ISSUE TITLE
Extending media with Lunar

### ISSUE THREAD

**Issue by KonstantinDyulin** [lunarphp/lunar#1971]
- Lunar version: 1.0.0-beta.2
- Laravel Version: 10.48
- PHP Version: 8.2
- Database Driver & Version: PostgreSQL 14.5.1

### Expected Behaviour:
Extend my own model to use media 

### Actual Behaviour:
When i try save some media for model that use a Lunar HasMedia trait i get an error:
![Снимок экрана 2024-09-27 124838](https://github.com/user-attachments/assets/c4429430-14a2-417a-a64a-51273f04d4b7)

### Steps To Reproduce:
Install Livewire Starter Kit
Add HasMedia Trait to User model
Try to add media for that model
![Снимок экрана 2024-09-27 124657](https://github.com/user-attachments/assets/2300b858-f01f-435e-8a1f-5b3778653a51)

**Comment by glennjacobs** [comment]
This isn't really a Lunar question, it's more for Spaties Media Library. I would suggest seeking support there

https://spatie.be/docs/laravel-medialibrary/v11/introduction

**Comment by KonstantinDyulin** [comment]
> This isn't really a Lunar question, it's more for Spaties Media Library. I would suggest seeking support there
> 
> https://spatie.be/docs/laravel-medialibrary/v11/introduction

No this is seem like a lunar question, because if i associate model with default Spaties HasMedia interface and InteractWithMedia trait, it works

**Comment by alecritson** [comment]
Using Spatie's default interface for your own custom models should be fine.
