### ISSUE TITLE
Booting time is more 1 seconds after installation

### ISSUE THREAD

**Issue by aalbarca** [lunarphp/lunar#1972]
- Lunar version: 1.0.0-beta.3
- Laravel Version: 11.1
- PHP Version: 8.2.23
- Database Driver & Version:

### Expected Behaviour:
Application booting time before instalation of Lunar package is 15ms.

### Actual Behaviour:
Application booting time after Lunar package installation is about 1-2 seconds.

### Steps To Reproduce:
I have a low performing VPS with several Laravel applications running perfectly.

After installing this package the entire application becomes non-functional as response times increase from a few ms to 1-2 seconds.

This is unacceptable since any change to a Livewire component takes seconds.

According to Debugbar the booting time exceeds 15 ms. to 2 seconds.

After removing the package everything is back to normal.

**Comment by glennjacobs** [comment]
Please can you provide detailed steps to reproduce. What do you mean by application? If you turn off the debugbar, do you get the same speed issue?

**Comment by aalbarca** [comment]
Hi  @glennjacobs 

1. I hire a "High Performance" instance on Vultr VPS (the cheapest one; 1GB of Memory; 1 virtual core)
2. I uploaded a e-commerce built with Laravel: https://tienda.modacora.es/ but **WITHOUT** Lunar package installed
3. The interaction with my website Livewire components is inmediate. If I click the button "Activar" then the coupon discount modal is openeded **immediately** 
4. I installed Lunar package following https://docs.lunarphp.io/core/installation.html
5. Then my website working slow. When I click the button "Activar" on my website the coupon modal component is opened 1 second later because ALL requests on my website are very very slow
6. If I uninstall the Lunar package everything returns to normal

Debugbar shows:
- Booting time with Lunar Package installed: 1500 ms
- Booting time without package: 15ms

I tried with `artisan optimize` and `composer optimize`

**Comment by aalbarca** [comment]
I fixed the problem:
https://stackoverflow.com/questions/74073036/why-does-this-laravel-package-increase-boot-process-by-3-seconds

Lunar installs the `blade-icons` package and the boostrapping time is fixed executing `artisan icons:cache`

**Comment by glennjacobs** [comment]
I see. I believe this is related to Filament.
