### ISSUE TITLE
Overall Performance is Sluggish & Slow

### ISSUE THREAD

**Issue by LeftPinkie** [lunarphp/lunar#1985]
- Lunar version: 1.0.0-beta.3
- Laravel Version: 11.26.0
- PHP Version: 8.2.20
- Database Driver & Version: MySQL 8.0.39

### Expected Behaviour:
With Livewire, expecting page navigation to be quick. That is one of the major purpose of Livewire and SPA. This will increase user experience.

### Actual Behaviour:
Navigating between pages are taking over 1.5 sec, sometimes 2.5+ secs, on just loading the initial Livewire data. This does not include loading subsequent data. This is the same for the storefront and the admin section. Are there any steps to improve performance or performance tuning on the roadmap for future consideration? I have enabled all the caches and disable DEBUG mode. The feature set of this package and the work put in are great but cannot be use in production if I have to wait 2+ sec for each page navigation.

**Comment by glennjacobs** [comment]
I'm sorry, but you have provided no steps to reproduce and I have not experienced this. Closing until more information is provided.
