### ISSUE TITLE
Products can not be attached to Collections

### ISSUE THREAD

**Issue by zakmcrbit** [lunarphp/lunar#2010]
- Lunar version: 1.0.0-beta.4
- Laravel Version: v10.48.22
- PHP Version: 8.2
- Database Driver & Version: MySQL

Products can not be attached to Collections. The **Product** dropdown field is always empty. What am I doing wrong?

![product](https://github.com/user-attachments/assets/e585c2ca-03db-4763-8044-71c0e506026c)

**Comment by glennjacobs** [comment]
I think this will be related to search. I always recommend using Laravel Scout as it gives a much better experience.

**Comment by zakmcrbit** [comment]
I have just installed Scout but still can't make it work ( Meilisearch throws Index products not found ). I will probably wait for #1986 and then try the database driver.

**Comment by zakmcrbit** [comment]
Update: I got it working using SCOUT_DRIVER=collection.
