### ISSUE TITLE
Detail page shouldn't throw error just because image is missing

### ISSUE THREAD

**Issue by zakmcrbit** [lunarphp/lunar#2014]
- Lunar version: 1.0.0-beta.4
- Laravel Version: 10.48.22
- PHP Version: 8.2
- Database Driver & Version: MySQL

### Expected Behaviour:

Detail-Page should be shown without the image.

### Actual Behaviour:

An error is thrown:
**App\Livewire\ProductPage::getImageProperty(): Return value must be of type Spatie\MediaLibrary\MediaCollections\Models\Media, null returned**

### Steps To Reproduce:
Create a product without uploading an image to the Media tab, then visit the product detail page in the frontend.

**Comment by glennjacobs** [comment]
What frontend are you referring to? It sounds like maybe this should be an issue on the Livewire starter kit?

**Comment by zakmcrbit** [comment]
You're right, my mistake.
