### ISSUE TITLE
No default Filament panel is set. You may do this with the `default()` method inside a Filament provider's `panel()` configuration.

### ISSUE THREAD

**Issue by maulik1211** [lunarphp/lunar#2022]
- Lunar version: 1.0.0-beta.6
- Laravel Version: 11.33.2
- PHP Version: 8.2.12
- Database Driver & Version: PostgreSQL 9.2

I am installing with the below steps.

1 | composer create-project laravel/laravel example-store
2 | create database example_store;
3 | Update composer.json"minimum-stability": "dev"
4 | composer require lunarphp/lunar:"^1.0.0-beta" -W
5 | php artisan lunar:install

### Expected Behaviour:
It should be installed without error.
### Actual Behaviour:
Getting error on 5th step (while migrating database): 
```
No default Filament panel is set. You may do this with the `default()` method inside a Filament provider's `panel()` configuration.

  at vendor/filament/filament/src/Exceptions/NoDefaultPanelSetException.php:17
```

**Comment by dualklip** [comment]
You have to register the admin panel

https://docs.lunarphp.io/core/installation.html#register-the-admin-panel

Is the step right before to make lunar:install 
https://docs.lunarphp.io/core/installation.html#run-the-artisan-installer

**Comment by maulik1211** [comment]
Got it, thanks
