### ISSUE TITLE
Creating an order does not reduce inventory

### ISSUE THREAD

**Issue by yasirmturk** [lunarphp/lunar#2024]
- Lunar version: 1.0.0-beta.5
- Laravel Version: 11.31.0
- PHP Version: 8.2.25
- Database Driver & Version: 10.6.20-MariaDB

### Expected Behaviour:

Inventory `In Stock` should be reduced by the quantity in order placed

### Actual Behaviour:

`In Stock` count remains the same 

### Steps To Reproduce:

Place an order

**Comment by glennjacobs** [comment]
No, currently it doesn't support that as we can't make the assumption that's what all stores will need. You would make your own order pipeline if you needed that behaviour. 

In the future we're looking at how we can incorporate this functionality into true inventory management.

**Comment by yasirmturk** [comment]
Can you please help me locate on how to make an order pipeline?

**Comment by glennjacobs** [comment]
> Can you please help me locate on how to make an order pipeline?

Take a look here https://docs.lunarphp.io/core/extending/orders.html

**Comment by yasirmturk** [comment]
Thanks Glenn, that is really helpful. Guess, I can also use this for Notification and sending transactional emails
