### ISSUE TITLE
CartSession addline - Attempt to read property "id" on null

### ISSUE THREAD

**Issue by ARMC0DE** [lunarphp/lunar#2039]
- Lunar version: 1.0.0-beta6
- Laravel Version: 11.33.2
- PHP Version: 8.3.14
- Database Driver & Version: Mysql 8.0.33

### Expected Behaviour:
I try in CartSession addline.
### Actual Behaviour:
Have error: Attempt to read property "id" on null

Full Code:

 public function addToCart(Request $request)
    {
        // Валидация входных данных
        $request->validate([
            'variant_id' => 'required|integer',
            'quantity' => 'required|integer|min:1',
        ]);

        // He Find
        //dd(\Lunar\Models\ProductVariant::find($request->variant_id));

        // Get error: Attempt to read property "id" on null
        CartSession::addLines([
            [
                'purchasable' => \Lunar\Models\ProductVariant::find($request->variant_id),
                'quantity' => $request->integer('quantity'),
            ],
        ]);
        
        return 1;
    }

**Comment by glennjacobs** [comment]
Can you provide the full stack trace or shared Flare error. 

Are you able to provide a failing test?

**Comment by shanerbaner82** [comment]
I get this too, just came here to see if this is a known issue. Unsure what I need to do differently (probably something in config?) for this to work.

[Here is my flare](https://flareapp.io/share/17W9zpjm)

**Comment by shanerbaner82** [comment]
@artur33s - 2 minutes after I posted my comment I figured out the issue, if you look at the Vendor Frames in Flare, it seems to be failing (for me at least) on the tax calculation. I assume, like me, you are using the demo store? If so, you can setup a tax class for that product or simply go to you config->lunar->cart and comment out 'Lunar\Pipelines\Cart\CalculateTax::class' from the 'cart' node.  Worked for me!

**Comment by glennjacobs** [comment]
Have you got taxes set-up correctly?

**Comment by ARMC0DE** [comment]
Im not using Taxes, but i add Zone Taxes and error not showing. Its work!

Thanks!
