### ISSUE TITLE
CartLine will intermittently return an incorrect unit price

### ISSUE THREAD

**Issue by daikazu** [lunarphp/lunar#325]
- GetCandy version: 2.0-beta13.1
- Laravel Version: 9.18.0
- PHP Version: 8.1.7
- Database Driver & Version:

### Expected Behaviour:
```php
$cartline->unitPrice->formatted(); //$9.12
```
### Actual Behaviour:
```php
$cartline->unitPrice->formatted(); //$9.11
```

### Steps To Reproduce:
I have a product variant with the price of $9.12. When added to cart it displays and calculates in the total as $9.11.

I have a forthcoming pull request to fix the issue.

**Comment by alecritson** [comment]
This should be sorted in `0.1.0-rc.1`
