### ISSUE TITLE
Move to using an off-the-shelf datatable

### ISSUE THREAD

**Issue by glennjacobs** [lunarphp/lunar#432]
Currently, our datatables for listing out orders, products, etc are custom to our needs. They work OK, but enhancing them to include more filtering and sorting, etc. will require a lot of work.

It is suggested we look to switch out to use a well-supported Livewire datatable package. 

At the moment we use Laravel Scout for searching, and most datatable packages will be using Eloquent and the query builder. For this reason (and others), we need to move away from our reliance on Laravel Scout for datatables and purely use it only for enhanced keyword searching.

This may bring up some challenges, as search engines do a great job of flattening data, making it very quick to display. Moving to the DB will potentially introduce performance issues on large datasets. We can look to overcome some of these potentially with well-written queries, e.g. filtering by date range first. We may even need to consider some denormalisation in the database.

The current main contender is [Filament Table Builder](https://filamentphp.com/docs/2.x/tables/installation), but we should consider all options before making a decision.

I would welcome everyone's thoughts so we can come to a decision on a way forward.

Tagging @adam-code-labx @alecritson

**Comment by adam-code-labx** [comment]
I would love to get into this discussion unfortunately currently have COVID symptoms so looks like need to cancel my family mini break. As soon as I am back in action next week I will contact Dan about your performance concerns. Meanwhile you can take a look here https://filamentphp.com/docs/2.x/tables/getting-started#searching-records-with-laravel-scout

**Comment by glennjacobs** [comment]
Oh the performance concerns are nothing to do with Dan's package. It's more our data and what we need to display.

**Comment by skyrowl** [comment]
Another suggestion would be [Livewire Powergrid](https://github.com/Power-Components/livewire-powergrid) havn't tested it yet tho it looks powerful and is linked within [WireUI website](https://livewire-wireui.com/) (may be interesting to take a look too)

**Comment by glennjacobs** [comment]
> Another suggestion would be [Livewire Powergrid](https://github.com/Power-Components/livewire-powergrid) havn't tested it yet tho it looks powerful and is linked within [WireUI website](https://livewire-wireui.com/) (may be interesting to take a look too)

It is very nice, but unfortunately, it doesn't properly support Laravel Scout, which we'll need for large datasets using JSON fields that need to be searched.

**Comment by alecritson** [comment]
We've introduced our own tables package to get started on `0.1.0-rc.1`
