### ISSUE TITLE
Customizing branding

### ISSUE THREAD

**Issue by wychoong** [lunarphp/lunar#458]
Currently there is no way to customize branding in the hub. Understand that it wouldn't be fair for getcandy as it won't get any promotion. However hub is used in back office so it won't gain much of the promotion, yet questioned by clients as engaged Company A but all branding is GC's. Perhaps this promoting can be more heavily focus for the frontend offered by GC in the future.

possible suggestion to this:
- only "powered by GetCandy" in footer, and can be disabled
- branding in official frontend

**Comment by glennjacobs** [comment]
I think changing the logo is ultimately what devs will want, on the login page and admin hub template.

We should always have something in the footer of the admin hub, probably with the version number.

The main thing for us to decide internally is whether this should be a premium feature.

**Comment by glennjacobs** [comment]
We've discussed this internally and are happy to run with the idea of allowing the logos to be rebranded, whilst keeping a footer entry, e.g. "GetCandy v2-beta14".

We won't look to make this a premium feature.

@alecritson would the best way be to allow the publishing of the logo components views?

**Comment by alecritson** [comment]
Yeah I'd say we could make the views publishable, should be doable

**Comment by adam-code-labx** [comment]
@alecritson I will also be looking to show my client a demo next week so need to add their logo to the hub.
Shall I put a PR together to publish those views or do you already have this one covered?

Will need to look into theming also at some point perhaps overriding the tailwind config will be good starting point?

@glennjacobs Regarding the footer perhaps can we say powered by GC v2.14b (not even sure we should have the b 👀)

GC is a fantastic developer tool but as you can imagine this would not look great to show our client's especially when the hub is still in beta.

**Comment by alecritson** [comment]
@adam-code-labx Happy for you to take a look. My initial thought was to have either two views, one for the collapsed logo and one for the expanded (which I assume would be also used on the login screen) and then have those two views publishable. What do you think @markmead @glennjacobs

**Comment by glennjacobs** [comment]
> @alecritson I will also be looking to show my client a demo next week so need to add their logo to the hub. Shall I put a PR together to publish those views or do you already have this one covered?
> 
> Will need to look into theming also at some point perhaps overriding the tailwind config will be good starting point?
> 
> @glennjacobs Regarding the footer perhaps can we say powered by GC v2.14b (not even sure we should have the b 👀)
> 
> GC is a fantastic developer tool but as you can imagine this would not look great to show our client's especially when the hub is still in beta.

Theming isn't something we will be considering. Branding is something we'll be handling internally. 

GetCandy is a product of ours and something we've invested lots of money into. It's a business. The brand is very important to us so it's a decision we need to be making internally.
