### ISSUE TITLE
Hub Orders Not Displaying

### ISSUE THREAD

**Issue by AugmentBLU** [lunarphp/lunar#462]
- GetCandy version: 2.0-beta14
- Laravel Version: 9.2.3
- PHP Version: 8.1
- Database Driver & Version: MariaDB 

### Expected Behaviour:
Should display a list of orders

### Actual Behaviour:
Gives this error.

```
MeiliSearch\Exceptions\ApiException
Json deserialize error: unknown field `facetsDistribution`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `showMatchesPosition`, `filter`, `sort`, `facets`, `highlightPreTag`, `highlightPostTag`, `cropMarker` at line 1 column 30 (View: /var/www/html/vendor/getcandy/admin/resources/views/livewire/components/orders/index.blade.php)
```

Orders are showing in Meili Search.

### Steps To Reproduce:
Install fresh Laravel project with Sail, install GetCandy as per instructions. 

This also happens using the demo-store repo. You can see individual orders if clicking through from a customer's history so it seems to be only the index list that's effected.

**Comment by glennjacobs** [comment]
I think this is a known issue. Meilisearch seems to have broken compatibility. It may work if you try an earlier version of Meilisearch. 

We're currently working on an update to simplify the Scout integration and offer a proper database option to get around the reliance on Meilisearch.

**Comment by AugmentBLU** [comment]
I'll check that out, thanks for the heads-up.

**Comment by wychoong** [comment]
not sure if related, but check your Meilisearch and meilisearch-php version https://github.com/meilisearch/meilisearch-php/issues/351#issuecomment-1184725136

**Comment by alecritson** [comment]
This should be sorted on `0.1.0-rc.1` as we've moved away from Meilisearch by default.
