### ISSUE TITLE
Orders page crash with fresh install

### ISSUE THREAD

**Issue by yasirmturk** [lunarphp/lunar#473]
- GetCandy version: 2.0@beta
- Laravel Version: 9.24.0
- PHP Version: 8.1.8
- Database Driver & Version: mysql

### Expected Behaviour: 
Page loads with empty collection

### Actual Behaviour: Page crashes with error

```Json deserialize error: unknown field `facetsDistribution`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `showMatchesPosition`, `filter`, `sort`, `facets`,
```

### Steps To Reproduce:
- Fresh install Laravel using laravel.build
- Install getcandy via composer 
- run all scripts and migration
- Login to admin hub and navigate to orders

**Comment by alecritson** [comment]
There was some breaking changes between Meilisearch versions it seems. We're looking at getting away from this on fresh installs, for the time being you can try putting the Meilisearch version to 0.24.0.

**Comment by yasirmturk** [comment]
I downgrades and also tried to run ms setup again but still same error only on order page

**Comment by yasirmturk** [comment]
`v0.24.0` Binary does not works with docker
<img width="660" alt="Screenshot 2022-08-28 at 15 43 40" src="https://user-images.githubusercontent.com/306691/187076912-19327d3a-434c-46ed-bc6e-a5d0cdf190e8.png">

**Comment by yasirmturk** [comment]
Well, binary `v0.25.2` + client `0.22.0` 👍

**Comment by alecritson** [comment]
This should be sorted on `0.1.0-rc.1`
