### ISSUE TITLE
Error in rollback migration "remove_formatting_columns_from_currencies_table"

### ISSUE THREAD

**Issue by armezit** [lunarphp/lunar#484]
- GetCandy version: 2.0-beta15
- Laravel Version: 9.23.0
- PHP Version: 8.1.8
- Database Driver & Version: 

### Expected Behaviour:
All migrations should be able to rolled back.

### Actual Behaviour:
One of the recent getcandy migrations, [remove_formatting_columns_from_currencies_table](https://github.com/getcandy/getcandy/blob/532623b4aa10a17dedf2851fb7c6d8137138d6cc/packages/core/database/migrations/2022_03_11_100000_remove_formatting_columns_from_currencies_table.php), throws error on rollback:

`PDOException: SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL`

The following 3 lines are in charge of the error:

https://github.com/getcandy/getcandy/blob/532623b4aa10a17dedf2851fb7c6d8137138d6cc/packages/core/database/migrations/2022_03_11_100000_remove_formatting_columns_from_currencies_table.php#L19-L21

This error is much annoying while testing new getcandy packages/addons, which depend on the getcandy migrations.
When test case is going to `tearDown` and rollback the migration, the exception throws and break the whole testing.

For this reason, getcandy migrations must be carefully tested to not to have such errors either in `up` or `down` methods.

### Steps To Reproduce:

Try to rollback that migration.

**Comment by alecritson** [comment]
The columns you have referenced aren't `nullable` in the original migration. If you are populating these tables in your tests you will need to make sure you have cleared the data before rolling back. Unless I'm missing something?

Also are you using the `Illuminate\Foundation\Testing\RefreshDatabase` trait on your tests?

**Comment by armezit** [comment]
> The columns you have referenced aren't `nullable` in the original migration. If you are populating these tables in your tests you will need to make sure you have cleared the data before rolling back. Unless I'm missing something?
> 
> Also are you using the `Illuminate\Foundation\Testing\RefreshDatabase` trait on your tests?

Yes I'm using `RefreshDatabase` trait. You are right, there should still be data in table. I missed that point, but I though RefreshDatabase clear data before rolling back?! Seems it's not though.

**Comment by alecritson** [comment]
From looking at the docs `RefreshDatabase` will only trigger when the schema has changed, so it's possible there are left over records, having said that I feel they should still be able to rollback on a populated database. I've put together #488 for this.

**Comment by alecritson** [comment]
This should be sorted on `0.1.0-rc.1`
