### ISSUE TITLE
Migrations: SQLite doesn't support multiple calls to dropColumn / renameColumn in a single modification

### ISSUE THREAD

**Issue by armezit** [lunarphp/lunar#485]
- GetCandy version: 2.0-beta15
- Laravel Version: 9.23.0
- PHP Version: 8.1.8
- Database Driver & Version: SQLite 3.39.0

### Expected Behaviour:
It's common to run db migrations in testing environments using SQLite in memory for better performance.
So, if it's possible, it's better to write migrations in a way that it runs on sqlite too.

### Actual Behaviour:
There are two known issues in laravel which prevent running migrations on sqlite:

One of them is `dropForeign` statements which sqlite does not support. But [there is solutions](https://github.com/laravel/framework/issues/25475#issuecomment-439342648) to avoid the problem in test cases, without touching migrations.

The second one is an old issue which throws the following error:
`SQLite doesn't support multiple calls to dropColumn / renameColumn in a single modification`

This one has a solution too. But it should be done in migration logic itself. The solution is simple: instead of multiple calls of `dropColumn` method, call it once with an array of column names.

For example, instead of:
```
$table->dropColumn('foo');
$table->dropColumn('bar');
```
use this:
```
$table->dropColumn(['foo', 'bar']);
```

There are 2 occurrences of such statements in the getcandy migrations:

https://github.com/getcandy/getcandy/blob/532623b4aa10a17dedf2851fb7c6d8137138d6cc/packages/core/database/migrations/2022_03_17_100000_add_fields_to_transactions_table.php#L28-L29

https://github.com/getcandy/getcandy/blob/532623b4aa10a17dedf2851fb7c6d8137138d6cc/packages/core/database/migrations/2022_01_12_100000_add_columns_to_attributes_table.php#L21-L23

The fix of these are simple, but the more important thing is that if we want to support sqlite for migrations (which I think is getting more important, as the ecosystem around getcandy grows bigger and more addons will be written for it), we should consider ways to ensure compatibility of migrations.

Otherwise, if we don't care about supporting sqlite for migrations, then documenting the incompatibility in Migrations section of documents would be very helpful for devs.

**Comment by philharmonie** [comment]
And what is the solution for 
```php
$table->renameColumn('for', 'bar');
```
