### ISSUE TITLE
Add Variant button does not work in variants show page

### ISSUE THREAD

**Issue by armezit** [lunarphp/lunar#491]
- GetCandy version: 2.0-beta15
- Laravel Version: 9.23.0
- PHP Version: 8.1.8
- Database Driver & Version:

### Expected Behaviour:
Add Variant button should display add variant slideover component

### Actual Behaviour:
Add Variant button does nothing. When inspected in browser dev tools (below image), the button has no any event handler attached. Seems that livewire components inside side-menu have not been activated.

![Screenshot from 2022-08-21 15-05-14](https://user-images.githubusercontent.com/2006991/185787270-21f90b2f-40f1-42e3-a4aa-0fc682e8bf1c.png)

I'm not much familiar with Livewire, but is it possible to be related with usage of `@section('menu')` in https://github.com/getcandy/getcandy/blob/532623b4aa10a17dedf2851fb7c6d8137138d6cc/packages/admin/resources/views/livewire/components/products/variants/show.blade.php ?

### Steps To Reproduce:

1. Create a product with variants
2. Open product variants edit page and click `Add Variant` button in side-menu

**Comment by adam-code-labx** [comment]
@armezit @alecritson 
I have tested and have the same issue on my side.
The problem is with the @section('menu') livewire won't function correctly using template inheritance.
I suggest we refactor using the component layout with x-slot

Alternatively and certainly the fastest workaround why not just move the button top left header variants show page?
This will solve the problem for now.

**Comment by adam-code-labx** [comment]
Perhaps a better way if we really want to have add variant to be in the sidebar is create a sidebar livewire component similar to collections

```html
@section('menu')
    <x-hub::layout.side-menu>
        @livewire('hub.components.collections.sidemenu', [
            'currentGroup' => $group ?? null,
        ])
    </x-hub::layout.side-menu>
@stop
```

**Comment by armezit** [comment]
> Perhaps a better way if we really want to have add variant to be in the sidebar is create a sidebar livewire component similar to collections

@adam-code-labx I think this is a better approach

**Comment by adam-code-labx** [comment]
Ok then I will put a PR fix together for this one tomorrow 👍
