### ISSUE TITLE
Tax_Breakdown of Order multiplication by number of items

### ISSUE THREAD

**Issue by AphgaDesign** [lunarphp/lunar#519]
- GetCandy version: 2.0@beta
- Laravel Version: 9.2
- PHP Version: 8.1
- Database Driver & Version: MySQL, 8.0.29

### Expected Behaviour: 
The Order's TaxBreakdown percentage at 5% for TPS (exemple)

### Actual Behaviour: 
![GetCandy-Bug-Tax_Breakdown](https://user-images.githubusercontent.com/17551643/189261535-fb64df87-e655-4110-a342-a595572d70fd.JPG)
When you create an Order from Cart, the Order's TaxBreakdown percentage are multiplicated by number of items in order (TPS of 5% are at 15% for an Order with 2 items and 1 shipping).

### Steps To Reproduce: 
1. Configure TPS at 5%
2. Configure TVQ at 9.975%
3. Add 2 items with 1 shipping option in cart
4. Create Order from Cart
5. Look tax_breakdown on Order's table in database.

**Comment by glennjacobs** [comment]
Can you please show your tax configuration? Depending on how you've set it up, this would be the correct behaviour.

We don't have enough information here to reproduce.

**Comment by AphgaDesign** [comment]
Ok, i show you the configuration in hub parameters and an exemple in a product
![GetCandy-Bug-Tax_Breakdown-1](https://user-images.githubusercontent.com/17551643/189345431-ca80b168-ff07-4e54-90f1-38bb73c47bd6.JPG)
![GetCandy-Bug-Tax_Breakdown-2](https://user-images.githubusercontent.com/17551643/189345433-914ecea2-293f-4333-9020-a39065cae4f3.JPG)

**Comment by glennjacobs** [comment]
You have configured two tax rates, so it's doing what is expected.

How do you need it to work?

**Comment by AphgaDesign** [comment]
In Quebec, we have TPS (5 %) and TVQ(9,975 %). In DB, the tax_breakdown for a product have right % for TPS and TVQ. But the tax_breakdown for an order have the wrong % because it was multiply by the number of lines in order

**Comment by AphgaDesign** [comment]
And an other information, in cart, the % is working fine but not in order

**Comment by glennjacobs** [comment]
Right I see, so the 5% for example should always be 5%, a percentage shouldn't increase (e.g. to 15%).

Apart from the percentages, are the other figures correct?

**Comment by glennjacobs** [comment]
FYI, I have been able to reproduce this.

**Comment by AphgaDesign** [comment]
> Right I see, so the 5% for example should always be 5%, a percentage shouldn't increase (e.g. to 15%).
> 
> Apart from the percentages, are the other figures correct?

No, all other informations seems right!

**Comment by AlexDanault** [comment]
You guys are FAST ! This is great news for this package :)

**Comment by alecritson** [comment]
This has been merged, tagged and released on to `0.1.0-rc.1`
