### ISSUE TITLE
Media-library collections are not properly implemented

### ISSUE THREAD

**Issue by tvlokven** [lunarphp/lunar#520]
I'd like to be able to use Spatie's Media-library to add additional (non-image) media to a product, e.g. PDF files like manuals or data sheets. I would store them in a different media collection than the one used by GetCandy for the images.

Currently the Hub uses the "products" and "variants" collections for the Products and ProductVariants respectively. However, the Hub ignores the collections and simply loads all the media for the products, and it treats all the media as images.

I think it would be an improvement to store all the images for each model in an "images" collection, and only use that collection for the images in the Hub. Also this collection could be used for the thumbnail relationship in the HasMedia trait, making sure only images are considered for thumbnails.

This would allow developers to attach additional media to Products and Variants without breaking the Hub.

However, renaming the collection could be a breaking change for existing front-ends that use the existing collections, so that's something to consider.

**Comment by tvlokven** [comment]
Created a pull request: https://github.com/getcandy/getcandy/pull/524

**Comment by alecritson** [comment]
This has been merged into develop and ready for the next release.
