### ISSUE TITLE
Cannot find vendor/lunar/livewire-tables/app.css?id=221199ffc920d5ade684160ac9868146

### ISSUE THREAD

**Issue by Aslam97** [lunarphp/lunar#586]
- Lunar version: ^0.1.0-rc.3
- Laravel Version: ^9.19
- PHP Version: 8.1.2

### Actual Behaviour:

![Screenshot from 2022-09-28 17-12-50](https://user-images.githubusercontent.com/25027592/192753586-e370009f-9e37-4a5c-86ee-ca1f89701888.png)

### Steps To Reproduce:

Install fresh laravel and lunar

**Comment by alecritson** [comment]
If you run the following

```
php artisan vendor:publish --tag=lunar.livewiretables.public --force
```

It should publish those assets for you, thanks for reporting, we'll get this included in the install going forward.

**Comment by nilsir** [comment]
> If you run the following
> 
> ```
> php artisan vendor:publish --tag=lunar.livewiretables.public --force
> ```
> 
> It should publish those assets for you, thanks for reporting, we'll get this included in the install going forward.

I tried it, it still doesn't work

**Comment by webspilka** [comment]
I have same problem now, my site works on https. What about you?

My site start works after I make changes in templates
`src/resources/views/layouts/storefront.blade.php` and `src/resources/views/layouts/checkout.blade.php`
I replace `asset` to `secure_asset`

```blade
{{-- for example I set --}}
href="{{ secure_asset('css/app.css') }}"
```
Tomorrow I will figure out how to make the `/hub` work as well.

Maybe someone can tell me how to make all links HTTPS?
in my .env I have 
```env
APP_URL=https://mysite.dev
```
