### ISSUE TITLE
Can no longer edit Variants without an SKU

### ISSUE THREAD

**Issue by CWFranklin** [lunarphp/lunar#608]
- Lunar version: 0.1-rc5
- Laravel Version: 9.32.0
- PHP Version: 8.1.10
- Database Driver & Version: mysql

### Steps To Reproduce:
- Mark SKU and all other identifiers as not required/unique in Product config
- Enable variants
- Add a variant without an SKU (or remove the autogenerated SKU if it makes one)

### Expected Behaviour:
Use of an edit button/image/options for edit button

### Actual Behaviour:
Edit behaviour is attached to the SKU which doesn't have to be a required field and can therefore not be present

**Comment by armezit** [comment]
I have this problem too. Maybe it's better add edit URL to variant thumbnail (in addition to SKU)

**Comment by alecritson** [comment]
This should no longer be an issue in v1
