### ISSUE TITLE
SKUs when not required are still auto-populated when not required

### ISSUE THREAD

**Issue by CWFranklin** [lunarphp/lunar#621]
- Lunar version: 0.1.0
- Laravel Version: 9.32.0
- PHP Version: 8.1.10
- Database Driver & Version: mysql

### Steps To Reproduce:
- Mark SKU as not required (but still unique) in Product config
- Create new product, add variants
- Create another new product, add the same variants again

### Expected Behaviour:
Don't auto-populate SKUs when they are not required. When they are required, populate with useful values that aren't duplicated by this system.

### Actual Behaviour:
SKUs are auto-populated with -1, -2 etc. These are auto-populated with the same values on each product and cause conflicts and therefore errors when saving the product itself or the variants.

**Comment by alecritson** [comment]
In version 1 you should be able to see and edit the SKU's which are being generated before saving occurs, this should help mitigate this problem.
