### ISSUE TITLE
Use GraphQL in the project?

### ISSUE THREAD

**Issue by ILDaviz** [lunarphp/lunar#629]
**Description**
The idea is to use GraphQL and Sanctum to go and communicate with the outside using GraphQL for api management.

**My Solution**
I was thinking of using LightHousePhp as a package for Laravel for data management, the interesting thing is that it uses eloquent and would go directly into dialogue with models except for special cases. For the authentication part I would leave the management to Sanctum then with a token to be added in the call header. For the multi-language management I envisioned a parameter to be passed in the call header so that the system is told which language it should handle for data extraction. Then on the Laravel side there will be middleware for the logic.

**Comment by glennjacobs** [comment]
This isn't something we plan to do any time soon. We have plans for a RESTful API. Closing this for now. I would suggest if it's wanted by some, that it is developed as a separate package for now.
