### ISSUE TITLE
Using a slot a the top of the products view crashes (http 403) after saving an existing product.

### ISSUE THREAD

**Issue by AlexDanault** [lunarphp/lunar#632]
- Lunar version: 0.1.1
- Laravel Version: 9.30.1
- PHP Version: 8.1.11
- Database Driver & Version: MySQL 8.0.28

### Expected Behaviour:

Slot sppears when editing a product and is re-displayed after saving the product.

### Actual Behaviour:

Slot sppears when editing a product but crashes (http 403) after saving the product.

### Steps To Reproduce:

- Create a new slot component:

```
<?php

namespace App\Http\Livewire\Components\Lunar\Hub\Slots;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;
use Lunar\Hub\Slots\AbstractSlot;
use Lunar\Hub\Slots\Traits\HubSlot;

class ProductSquareSyncSlot extends Component implements AbstractSlot
{
    use AuthorizesRequests;
    use HubSlot;

    public static function getName()
    {
        return 'hub.product.slots.product-square-sync';
    }

    public function getSlotHandle()
    {
        return 'product-square-sync';
    }

    public function getSlotInitialValue()
    {
        return [];
    }

    public function getSlotPosition()
    {
        return 'top';
    }

    public function getSlotTitle()
    {
        return 'product-square-sync';
    }

    public function updateSlotModel()
    {
    }

    public function handleSlotSave($model, $data)
    {
        $this->slotModel = $model;
    }

    public function render()
    {
        return view('livewire.components.lunar.hub.slots.product-square-sync');
    }
}

```

- Create the slot's view:

```
<div class="rounded-md p-4 bg-blue-50">
    <div class="flex items-center">
        <div class="flex-shrink-0">
            <div class="text-blue-500">
                <div>
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M13 16H12V12H11M12 8H12.01M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                </div>
            </div>
        </div>
        <div class="flex-1 ml-3 md:flex md:justify-between w-full">
            <div class="text-sm text-blue-700">
                Hey ! Je suis en haut d'un produit !!

                <br />
                #{{ $slotModel->id }} - {{ $slotModel->brand }}
            </div>
        </div>
    </div>
</div>
```

- Register the slot in a service provider:

```
Slot::register('product.show', ProductSquareSyncSlot::class);
```

- Go in the admin hub, display an existing product
- See that the slot is present (yes)
- Change the product name, save
- The product is saved, but livewire fires a 403 during a POST to the slot's component:

![image](https://user-images.githubusercontent.com/4428772/194785768-c8ed5e02-e1d7-4d9f-90aa-391647f8f334.png)

![image](https://user-images.githubusercontent.com/4428772/194785785-ea655c18-b482-408d-ad29-60697902bd58.png)

- Telescope reveals which gate refused the action:

![image](https://user-images.githubusercontent.com/4428772/194786004-e7e89041-3fe4-470a-8021-9221716e37c4.png)

![image](https://user-images.githubusercontent.com/4428772/194786008-a7be1a7f-1a0b-4bb6-beb1-6f32d26877b8.png)

I made sure that the slot's namespace includes `Lunar` or `Hub` so that the propre middlewares are applied, as the doc states.

The `AuthorizesRequests` is an attempt to fix, but doesn't change anything.

**Comment by alecritson** [comment]
Looks like the docs were incorrect, I've opened a quick PR to fix this, the naming should be:

```php
public static function getName()
{
    return 'hub.components.products.slots.product-square-sync';
}
```
