### ISSUE TITLE
Cannot Remove Brand

### ISSUE THREAD

**Issue by Aslam97** [lunarphp/lunar#638]
- Lunar version: 0.1.1
- Laravel Version: 9.35.1
- PHP Version: 8.1.2
- Database Driver & Version: MySQL 8.0.30-0ubuntu0.22.04.1

### Expected Behaviour:
The brand is deleted because there are no products associated with the brand

### Actual Behaviour:
```mysql
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`foo`.`lunar_products`, CONSTRAINT `lunar_products_brand_id_foreign` FOREIGN KEY (`brand_id`) REFERENCES `lunar_brands` (`id`))
```

### Steps To Reproduce:
1. Create new brand call **Test**
2. Create new product call **Product Test** and assign the product to **Test** brand
3. Delete **Product Test** product. after product status is `deleted` now Delete the  **Test** brand

**Comment by glennjacobs** [comment]
Looks like we shouldn't be allowing a brand to be deleted if it's being used by a product.
