### ISSUE TITLE
$this->product->translateAttribute('description') echos HTML

### ISSUE THREAD

**Issue by errand** [lunarphp/lunar#650]
- Lunar version: 0.1.1
- Laravel Version: 9.x
- PHP Version: 8.1
- Database Driver & Versi#on: MariaDB-10.5

### Expected Behaviour:
Html description
### Actual Behaviour:
<p>Html description</p>
### Steps To Reproduce:
Fill the description attribute and publish product

Fixed this using {!! $this->product->translateAttribute('description') !!}

**Comment by markmead** [comment]
Hi @errand I'm unsure what the issue is here. 

It's a WYSIWYG editor that has options for different font styles, it needs to be in HTML.

**Comment by errand** [comment]
Hi, @markmead , it renders as plain text with tags on the front end :)

**Comment by alecritson** [comment]
This is correct behaviour as Laravel will auto escape the HTML :)
