### ISSUE TITLE
Pricing changes when saved in hub

### ISSUE THREAD

**Issue by ryanmitchell** [lunarphp/lunar#662]
- Lunar version: 0.1.0-rc.5
- Laravel Version: 8.83.25
- PHP Version: 8.1.8
- Database Driver & Version: MySQL 8

### Expected Behaviour:

When I enter a price of 18.99 into the price fields in the hub, they get saved as 18.98...

### Actual Behaviour:

The price I enter is saved.

### Steps To Reproduce:

I've narrowed the issue down to[ this line](https://github.com/lunarphp/lunar/blob/9194dd7f8c53c4e8e5a10f3fb409498430524bae/packages/admin/src/Actions/Pricing/UpdatePrices.php#L58)

The price starts at 18.99, by the currency factor becomes 1899.0 and then by the int casting becomes 1898... so very strange. I've tried changing it to use intval instead of casting as an int, but it does the same.

Maybe you just need to treat it as a string and strip what comes after the decimal away?

**Comment by alecritson** [comment]
@ryanmitchell I've put together a PR #692 to address this. It makes use of the bcmath extension, which considering is a requirement by Laravel, should be safe to use.
