### ISSUE TITLE
Fallback Image

### ISSUE THREAD

**Issue by charlielangridge** [lunarphp/lunar#681]
**Is your feature request related to a problem? Please describe.**
Spatie Media Library has the functionality to have one / multiple fallback images if a model doesnt have media attached - this would prevent either an error if a getUrl() is called, or a broken image

**Describe the solution you'd like**
By implementing the registerMediaCollections() function on the "hasMedia" trait to establish the 'image' collection that lunar uses, the fallback url / path could be setup. I'd suggest that the fallback image url be a env variable, referenced through the lunar.media config file

**Describe alternatives you've considered**
There doesnt seem an obvious way to do this without altering the lunar code

**Additional context**
I'm happy to add this code via fork & pr

**Comment by charlielangridge** [comment]
I've built this feature and added a PR - https://github.com/lunarphp/lunar/pull/682

**Comment by alecritson** [comment]
Thanks @charlielangridge It's been merged and will be in the `0.2` release 🥳
