### ISSUE TITLE
http://<yoursite>/hub/login Login fails

### ISSUE THREAD

**Issue by zmoyi** [lunarphp/lunar#704]
- Lunar version: 0.1.3
- Laravel Version: 9.33.0
- PHP Version: 8.0.02
- Database Driver & Version:mysql5.7.39

### Expected Behaviour:
Performing login operations

### Actual Behaviour:
![image](https://user-images.githubusercontent.com/48953751/201454700-56b3f41f-323c-4010-b81c-77da9760b466.png)

### Steps To Reproduce:

**Comment by dawwwid** [comment]
I think the path to Livewire assets is wrong.

Try to use the command: `php artisan livewire:publish --config`

And to modify the value of `asset_url` in `config/livewire.php` by adding the path to your project. (ex: `/lunar/demo/public`)

**Comment by chrysos** [comment]
`php artisan livewire:publish --assets`
