### ISSUE TITLE
There is no edit url for product variants without SKU

### ISSUE THREAD

**Issue by armezit** [lunarphp/lunar#705]
- Lunar version: 0.1.3
- Laravel Version: 9.39.0
- PHP Version: 8.1
- Database Driver & Version:

### Expected Behaviour:

There should be some link / button for editing product variant.

### Actual Behaviour:

The only clickable part of product variant edit is it's SKU. So, there's no way to edit a product variant without SKU.

![Screenshot from 2022-11-12 16-28-44](https://user-images.githubusercontent.com/2006991/201475425-636c5a3e-c5d1-4639-af90-61ef3b7221d2.png)

I'm suggesting one of these improvements:
- change `Options` to a clickable link (just like SKU)
- add an edit link (as the last table column)
- make thumbnail clickable

Please share your idea.

**Comment by armezit** [comment]
This is a duplicate of the issue #608

**Comment by alecritson** [comment]
This should no longer be an issue in v1
