### ISSUE TITLE
Dashboard - chart should be updated when the date changes. without having to refresh the page

### ISSUE THREAD

**Issue by Aslam97** [lunarphp/lunar#710]
When date changed chart should update too. right now i need to refresh the page in order to see the updated chart

### Actual Behaviour:

https://user-images.githubusercontent.com/25027592/201630666-909233cc-f3f6-430e-b988-e7f8b1dd85ac.mp4

**Comment by alecritson** [comment]
Thanks @Aslam97 We've got some big plans for the dashboard to make it extensible and more widget based.

**Comment by Aslam97** [comment]
@alecritson You guys always amaze me. can't wait to see what you guys working on. in the meantime I will just close this issue
