### ISSUE TITLE
Product not found after product created

### ISSUE THREAD

**Issue by Aslam97** [lunarphp/lunar#726]
- Lunar version: 0.1.4

### Expected Behaviour:

Product found after page reload.

### Actual Behaviour:

After page reload product id not found and **modal page not found** show up

> **please note that this does not happen all the time while creating the product**

![Screenshot from 2022-11-17 15-51-15](https://user-images.githubusercontent.com/25027592/202400664-b5ab769e-bb6c-4c9e-b38a-821b30088aca.png)

### Steps To Reproduce:

1. set `QUEUE_CONNECTION` to `redis`
2. run queue
3. Go to Product
4. Create new product
5. Add variant
6. Hit save

**Comment by alecritson** [comment]
@Aslam97 Is this still an issue? I just tried on `0.2` and was able to create a product fine.

**Comment by Aslam97** [comment]
@alecritson I believe this issue is no longer relevant since I have not tested it on the latest version. Therefore, I will just close this issue.
