### ISSUE TITLE
Discount coupons

### ISSUE THREAD

**Issue by illumws** [lunarphp/lunar#734]
**Is your feature request related to a problem? Please describe.**
I'm creating a store but I noticed that there is no way to apply discounts on products in the form of a coupon

**Describe the solution you'd like**
Create a screen where I can register discount coupons

**Describe alternatives you've considered**
...

**Additional context**
I think it would be interesting to have a coupon association based on:
product collections, group of customers and individual products

**Comment by illumws** [comment]
https://github.com/lunarphp/lunar/pull/324

**Comment by glennjacobs** [comment]
We have a PR for this currently and an existing issue, so closing this. It will be released in 0.2
