### ISSUE TITLE
Settings link auto redirects to attributes, but a user may not have that permission

### ISSUE THREAD

**Issue by markmead** [lunarphp/lunar#742]
Need to send the user to the first available page, not attributes.

Or, we have a dashboard page for settings that lists out all available links 🤷‍♂️

**Comment by glennjacobs** [comment]
True true! Good spot.

**Comment by alecritson** [comment]
> Need to send the user to the first available page, not attributes.
> 
> Or, we have a dashboard page for settings that lists out all available links 🤷‍♂️

Personally I think listing out is better since then we don't have to grab all the pages, loop through and figure out which one to redirect to.

**Comment by AlessandroAmos** [comment]
I created an issue about this... can I close it?
https://github.com/lunarphp/lunar/issues/739#issue-1456677626

**Comment by markmead** [comment]
> I created an issue about this... can I close it?

Sorry, @AlessandroAmos I didn't see yours when creating this, my bad! 

It makes sense to close it and use this one as there's been some discussion. Sorry again.
