### ISSUE TITLE
Missing translatable components and overflowing date on tables

### ISSUE THREAD

**Issue by skyrowl** [lunarphp/lunar#748]
- Lunar version: 0.1.4

### Expected Behaviour:
Every texts should be translatable within the hub
Date should be displayed clearly

### Actual Behaviour:
Some texts are missing translations
Date is not readable when selecting a range

### Steps To Reproduce:
The best example is the "Orders" tab within the hub

![image](https://user-images.githubusercontent.com/66191586/203620135-81300f2f-bae4-409d-9436-23dfacbf0c4a.png)
(Every english words are missing translations, for clarity "Statut" is a translated word)

**Comment by markmead** [comment]
Good spot! @skyrowl Are you interested in taking a look at these?

**Comment by alecritson** [comment]
Closing due to now using Filament panel
