### ISSUE TITLE
SystemTaxDriver only works with postcode-based tax zones

### ISSUE THREAD

**Issue by webcraft** [lunarphp/lunar#755]
- Lunar version: 0.1.4
- Laravel Version: 8.83.26
- PHP Version: 8.1.8
- Database Driver & Version: mysql 8

### Expected Behaviour:
I added country based tax zones, one for every country in the EU. I expect the `SystemTaxDriver` to use the appropriate tax zone depending on the shipping address country.

### Actual Behaviour:
In reality, it always uses the default tax zone.
The `GetTaxZone` class seem to only take into account postcode-based tax zones. So also no state-based tax zones.

### Steps To Reproduce:
Add some country based tax zones with different tax rates (and no postcode based ones).
Do a checkout and change the shipping address country.
Observe that the tax rate never changes but is always the default one.

**Comment by alecritson** [comment]
@webcraft Was this resolved in your PR #1248

**Comment by alecritson** [comment]
Closing as this should be resolved from `0.5.5`
