### ISSUE TITLE
UpdatePrices Action

### ISSUE THREAD

**Issue by ItzEscalitur** [lunarphp/lunar#757]
- Lunar version: 0.1.4
- Laravel Version: v8.83.26
- PHP Version: v8.1
- Database Driver & Version: MySQL

### Expected Behaviour:
When a product is created or updated the compare price should be saved.

### Actual Behaviour:
Instead of the compare price being saved, the price is being saved for both variables.

### Steps To Reproduce:
UpdatePrices Action inside updateOrCreatePrice the data passed into the fill function of the
price model are incorrect. 
Instead of `$comparePrice ? (int) bcmul($price, $currency->factor) : null` it should be
`$comparePrice ? (int) bcmul($comparePrice, $currency->factor) : null`.

**Comment by markmead** [comment]
Fixed with #759, thanks for the report @ItzEscalitur.
