### ISSUE TITLE
Demo store Class "NumberFormatter" not found

### ISSUE THREAD

**Issue by aljazromih** [lunarphp/lunar#758]
- Lunar version: 0.1.4
- Laravel Version: 8.83.26
- PHP Version: 8.0.25

### Actual Behaviour:
I get the following error in Demo store:

> Class "NumberFormatter" not found (View: `.../resources/views/components/product-price.blade.php`)
`vendor/lunarphp/lunar/packages/core/src/DataTypes/Price.php:75`

### Steps To Reproduce:
[Demo store](https://docs.lunarphp.io/quickstart.html#demo-store)

**Comment by glennjacobs** [comment]
This isn't a bug, you are missing the PHP extension.

You need to enable the intl PHP extension. See https://docs.lunarphp.io/installation.html#requirements
