### ISSUE TITLE
Unable to Upload Product Images on Vapor

### ISSUE THREAD

**Issue by kylekanderson** [lunarphp/lunar#764]
- Lunar version: 0.1.4
- Laravel Version: 9.41.0
- PHP Version: 8.1.12
- Database Driver & Version: MySQL 8

### Expected Behaviour:
I am able to upload product images for products in the Admin Hub

### Actual Behaviour:
When uploading a product image in the Admin Hub using the standard FilePond upload component, I am able to see the image thumbnail next to the image. However, when clicking on "Save Product" I receive the following error:

"File livewire-tmp/s0MGjzvQNW3ps80ou26HVsnJ4Y1ofK-metaUl9lNTM4MDU2MC1kMmZlLTRmYjEtODY0ZS1kNjc4YTE4OTk3ZTMuanBnLnBuZw==-.png does not exist"

### Steps To Reproduce:
In a Laravel Vapor environment, attempt to upload a product image in the Admin Hub

**Comment by glennjacobs** [comment]
What storage method are you using? S3?

**Comment by kylekanderson** [comment]
> What storage method are you using? S3?

Yes, S3

**Comment by glennjacobs** [comment]
It's just Spatie Media Library under the hood and I've not heard of any other users having issues. However, I'll ask the guys to check on their installs in the morning to see if they're having issues with S3.

**Comment by kylekanderson** [comment]
Thanks. Yeah, I think it's how the HasImages trait is using spatie media library. I'm wondering if this existing PR may resolve this: [https://github.com/lunarphp/lunar/pull/701](https://github.com/lunarphp/lunar/pull/701)

Will try ^ that out and report back.

**Comment by kylekanderson** [comment]
Okay, yeah can confirm PR [https://github.com/lunarphp/lunar/pull/701](https://github.com/lunarphp/lunar/pull/701) resolves this for me.

**Comment by glennjacobs** [comment]
We should get that merged, will raise it tomorrow with the team.

**Comment by kylekanderson** [comment]
That would be great! Thanks so much for your help @glennjacobs. Really enjoying using this package so far.
