### ISSUE TITLE
Menu doesn't scroll when menu items gets to certain size.

### ISSUE THREAD

**Issue by alecritson** [lunarphp/lunar#774]
Currently the way the layout has been put together has a couple of side effects, most notably once the amount of menu items exceeds what can be viewed on the page, it doesn't scroll, so you get locked out of the other area's.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/1488016/208455051-1cef20ed-85a5-49b7-9390-11c3a45a0467.png">

**Comment by markmead** [comment]
I've looked into this. It's annoying as you can't add a scroll to the whole side menu as it will cut off the toggle buttons.

I tried each menu group/section having a max height with inner scrolling which works but to me, it felt odd, would be something to try first. However, that isn't a full solution as you could have 30+ menu groups/sections with 10+ links each... No amount of inner scroll will stop that breaking.

Unless there are any better ideas, we're back to the whole side menu scrolling but we'll need a solution for the buttons.
