### ISSUE TITLE
Search in collections

### ISSUE THREAD

**Issue by afbora** [lunarphp/lunar#779]
**Is your feature request related to a problem? Please describe.**

I am searching for a collection while selecting a collection for the product in the product add form. Cannot find results without entering the full name of the collection.

![image (8)](https://user-images.githubusercontent.com/3393422/208923601-c12707ba-d90d-4025-8a48-e32495ff5071.png)

As you can see in the screenshot, no results were found. But when you type `Hoodies` the result is found.

Lunar 0.1.5

**Comment by alecritson** [comment]
Which search engine are you using, have you indexed everything?

**Comment by afbora** [comment]
No search engine, so using as default `SCOUT_DRIVER` and I've checked `search_index` from DB and I can see `Hoodies` record. But I can't find what I'm looking for without entering full words.

**Comment by glennjacobs** [comment]
The basic database Scout driver simply uses `whereFullText()` for searching. So it will cater for minor spelling issues etc, but won't perform prefix searches.

If you want a better search I would suggest considering Meilisearch, Typesense or Algolia.

If you want to have a play, you can look at https://github.com/lunarphp/lunar/tree/main/utils/scout-database-engine and see if you can make any improvements.

**Comment by afbora** [comment]
Thanks @glennjacobs Yes, you are right. I've searched a bit and full-text search can be solved in boolean mode and with asterisk. 

https://dev.mysql.com/doc/refman/8.0/en/fulltext-boolean.html

I've tested with following changes and seems works great for me. But I still don't know what side effects it has.

````php
protected function getSearchQuery(Builder $builder)
{
    $index = $this->getIndexFromBuilder($builder);

    return SearchIndex::where('index', '=', $index)
        ->whereFullText('content', $builder->query . '*', ['mode' => 'boolean']);
}
````

**Comment by glennjacobs** [comment]
Maybe make a PR for the change and we can see?

**Comment by afbora** [comment]
@glennjacobs I've created a new PR https://github.com/lunarphp/lunar/pull/808 I hope it's acceptable.
