### ISSUE TITLE
CartSession::forget(); not forgetting the session

### ISSUE THREAD

**Issue by charlielangridge** [lunarphp/lunar#782]
- Lunar version: dev-develop
- Laravel Version: 9.45.1
- PHP Version: 8.1.3
- Database Driver & Version: mysql-8.0.22-win64

### Expected Behaviour:
`$order = $cart->getManager()->createOrder();` does not clear the cart from the user's session.
so we call `CartSession::forget();  ` before redirect to success screen and it should remove the cart from the user

### Actual Behaviour:
It doesn't remove the cart from the session

**Comment by alecritson** [comment]
@charlielangridge I'd say this is intended behaviour as the cart manager isn't aware of the CartSession. Down the line when we have API integrations which are stateless it wouldn't make sense for the Cart Manager to try and purge itself from the session.

Also it would be somewhat of an assumption to forget the cart when an order is created, it should be up to the storefront to decide when it needs to forget it IMO.
