### ISSUE TITLE
Deleting a language fails on foreign key constraint

### ISSUE THREAD

**Issue by rubenvanerk** [lunarphp/lunar#785]
- Lunar version: 0.1.5
- Laravel Version: 9.45.1
- PHP Version: 8.1.13
- Database Driver & Version: MySQL 8.0.13

### Expected Behaviour:

Deleting a language doesn't throw errors and deletes the language.

### Actual Behaviour:

Deleting a language throws an error.

Stack trace: https://flareapp.io/share/DPyDZWbm#F64

### Steps To Reproduce:

1. Add a new language **and make it default**
2. Add a new product
3. Make another language default
4. Delete the language added in step 1

In the comment of the delete function in `LanguageShow.php` it says that it should soft delete the language model, but the model doesn't have the `deleted_at` column and doesn't use the `SoftDeletes` trait.

**Comment by alecritson** [comment]
@rubenvanerk I see the PR you put together has closed, can this issue also be closed? Is it still a problem?

**Comment by rubenvanerk** [comment]
The PR was a botched attempt at creating a failing test. The issue still persists.
