### ISSUE TITLE
doctrine/dbal compatibility issue

### ISSUE THREAD

**Issue by mebron** [lunarphp/lunar#820]
- Lunar version: 0.1.6
- Laravel Version: 9.48.0
- PHP Version: 8.1.2

Unable to Install, getting following error

Problem 1
    - Root composer.json requires lunarphp/lunar ^0.1.6 -> satisfiable by lunarphp/lunar[0.1.6].
    - lunarphp/lunar 0.1.6 requires doctrine/dbal 3.3.7 -> found doctrine/dbal[3.3.7] but it conflicts with your root composer.json require (^3.5).

**Comment by alecritson** [comment]
I assume this isn't a fresh Laravel install? Potential fix would be to use the same version that's locked in Lunar

**Comment by mebron** [comment]
Got it, try the latest version of doctrine/dbal in the next release

**Comment by alecritson** [comment]
Would be happy to see a PR for this if you think it's needed and have the time

**Comment by st3ph** [comment]
Same issue with a fresh install

**Comment by glennjacobs** [comment]
@alecritson recon we can change it from

```
"doctrine/dbal": "3.3.7",
```

to

```
"doctrine/dbal": "^3.3.7",
```

?

**Comment by alecritson** [comment]
> Same issue with a fresh install

Which version of Laravel?

**Comment by glennjacobs** [comment]
I've just installed Lunar to a fresh install of Laravel using PHP 8.0, 8.1 and 8.2 and couldn't reproduce it.

Could it be you have "doctrine/dbal" installed globally in composer? I'm just guessing.

**Comment by st3ph** [comment]
Laravel v9.47.0 running in it's docker (using curl -s https://laravel.build/example-app | bash)
