### ISSUE TITLE
This is raising an issue when uploading media

### ISSUE THREAD

**Issue by anejjar** [lunarphp/lunar#821]
https://github.com/lunarphp/lunar/blob/97504d1a515311395990265030b14cbad4768d70/packages/admin/src/Http/Livewire/Traits/HasImages.php#L223

![image](https://user-images.githubusercontent.com/31830418/213889709-1751cfaf-bbd9-4e54-8b0d-9712cf471465.png)

**Comment by alecritson** [comment]
This should be fixed in #853
