### ISSUE TITLE
Using pluck() on null on discount creation page

### ISSUE THREAD

**Issue by skyrowl** [lunarphp/lunar#830]
- Lunar version: 0.2.0-rc1
- Laravel Version: 9.48.0
- PHP Version: 8.1.3

### Expected Behaviour:
Show the create form of discounts

### Actual Behaviour:
Throws error
```
Call to a member function pluck() on null
```
pointing to "packages/admin/resources/views/partials/forms/discount/limitations.blade.php"
https://github.com/lunarphp/lunar/blob/937d946f17eb2fc9c79a3bbc6eaa5304118c4885/packages/admin/resources/views/partials/forms/discount/limitations.blade.php#L144-L147

### Steps To Reproduce:
Open discounts tab then click on "Create"
The install was upgraded from a previous version of lunar (upgrade guide has been followed) and is seeded with the demo store datas (not using demo store only its seeder)

**Comment by alecritson** [comment]
Resolved in #834
