### ISSUE TITLE
Creating/editing attribute groups crashes when there is more than 1 language

### ISSUE THREAD

**Issue by fakeheal** [lunarphp/lunar#836]
### Stack:

- Lunar version: 0.2-rc1
- Laravel Version: 9.19
- PHP Version: 8.2.1
- Database Driver & Version: MySQL 8

### Expected Behaviour:
To be able to create or edit attribute groups without issues.

### Actual Behaviour:

Livewire "crashes" with:

> **Livewire \ Exceptions \ CannotBindToModelDataWithoutValidationRuleException**
> Cannot bind property [attributeGroup.name.en] without a validation rule present in the [$rules] array on Livewire component: [lunar.hub.http.livewire.components.settings.attributes.attribute-group-edit].

### Steps To Reproduce:

Add more than one language and try creating a an attribute group.

Potential fix is replacing [`AttributeGroupEdit@rules`](https://github.com/lunarphp/lunar/blob/main/packages/admin/src/Http/Livewire/Components/Settings/Attributes/AttributeGroupEdit.php#L40)'s contents with: 

```php
public function rules()
{
    $rules = [];

    $this->languages->each(function ($language) use (&$rules) {
        $rules["attributeGroup.name.{$language->code}"] = array_merge(
            ['string', 'max:255'],
            $language->default ? ['required'] : []
        );
    });

    return $rules;
}
```
so all fields for each language have validation rules applied and only the `defaultLanguage` is `required`.

**Comment by alecritson** [comment]
@fakeheal I assume this was fixed with your PR #839 ?

**Comment by fakeheal** [comment]
@alecritson No, it's a separate issue. The one in #839 is for filling out attributes in the product page, but this one is for an error that occures when adding/editing attribute groups in Settings.

I opened a PR at #858.

**Comment by fakeheal** [comment]
Closing this as PR #858 is approved and merged. Hopefully, everything works fine 🤞 😄
