### ISSUE TITLE
imrovement to Discount module

### ISSUE THREAD

**Issue by wychoong** [lunarphp/lunar#842]
**Is your feature request related to a problem? Please describe.**
The way how Discount works is a little confusing, maybe is due to the doc is not ready. few things to clarify:
- Discounts are apply on which level, cart or cartLine
- can the Discount stacked
     - currently only the highest/last discount is applied
- how to get which Discount is applied to the cart or cartLine
     - currently when have multiple discounts, only the last is applied, but `$cart->discounts` still contains the all discounts
- when a cart have coupon code `OFF10`, and the only active discount available is without coupon code, should it be applied

**Describe the solution you'd like**
- able to retrieve applicable discounts for a product
- able to apply discount to cart and also cartLine

**Describe alternatives you've considered**
- to have more robust api for the discount type abstract class so can customise
- add prebuilt pipelines to swap in
- more examples in the doc

example shopee ecomm can apply discount on cart and item
![IMG_7874](https://user-images.githubusercontent.com/67364036/216320854-15f5645c-0e1a-4b5c-b1ea-2cc7f7121865.png)

**Comment by glennjacobs** [comment]
@wychoong should this be closed now?

**Comment by wychoong** [comment]
> @wychoong should this be closed now?

Sure
