### ISSUE TITLE
Unable to delete ProductOption

### ISSUE THREAD

**Issue by tvlokven** [lunarphp/lunar#843]
When I try to delete a ProductOption programmatically, I get the following error:

`Lunar\Models\ProductOption::Spatie\MediaLibrary\{closure}(): Argument #1 ($model) must be of type Spatie\MediaLibrary\HasMedia, Lunar\Models\ProductOption given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 421`

This is because the ProductOption model uses the `Lunar\Base\Traits\HasMedia` trait, which in turn uses the `Spatie\MediaLibrary\InteractsWithMedia` trait.

The InteractsWithMedia trait adds the following event listener:

```php
public static function bootInteractsWithMedia()
{
    static::deleting(function (HasMedia $model) {
        ...
    });
}
```

However, this typehinted HasMedia interface refers to the `Spatie\MediaLibrary\HasMedia` interface, which is unrelated to the `Lunar\Base\Traits\HasMedia` trait, resulting in the error.

I think the solution would be to havbe every model that uses the `Lunar\Base\Traits\HasMedia` trait implement the `Spatie\MediaLibrary\HasMedia` interface. Currently the only model that seems to do so is the Product model

- Lunar version: 0.1.5
- Laravel Version: 9.47.0
- PHP Version: 8.2.0
- Database Driver & Version: MySQL 8.0

**Comment by alecritson** [comment]
Hi @tvlokven this should be resolved in `0.2`
