### ISSUE TITLE
Cannot use object of type League\Flysystem\Config as array

### ISSUE THREAD

**Issue by facu-alba** [lunarphp/lunar#851]
Hello everyone. This error arises when loading images in a product. How to solve it? Regards

![image](https://user-images.githubusercontent.com/47679766/218270735-d72e2f8b-0737-428a-b070-4a32ea2da75f.png)

![image](https://user-images.githubusercontent.com/47679766/218270772-028e2ba3-0544-48b7-8219-768337bb387e.png)

**Comment by wychoong** [comment]
can you provide more context?

- the steps to reproduce
- what driver you using

**Comment by facu-alba** [comment]
Hi @wychoong. 

Steps: 

1. go to  /hub/products/create.
2. In the image section upload a new image.
3. Complete the required sections.
4. Click on save product button.

Also occurs when editing a product.

After click on the button prompts the error: Cannot use object of type League\Flysystem\Config as array

The driver is local. FILESYSTEM_DRIVER=local in the .env file

The propiertie "require" in my composer.json is: 

"require": {
        "php": "^7.3|^8.0",
        "fruitcake/laravel-cors": "^2.0",
        "lunarphp/admin": "^0.1",
        "guzzlehttp/guzzle": "^7.0.1",
        "http-interop/http-factory-guzzle": "^1.2",
        "laravel/framework": "^8.75",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5",
        "lunarphp/stripe": "^0.1"
    }
   
Thanks for your answer.

**Comment by wychoong** [comment]
@facu-alba can't replicate

can you share more specific info (eg: the actual installed version of packages: laravel, lunar)
or share the output of `php artisan about`

also are you doing anything special with the filesystem driver?

**Comment by alecritson** [comment]
I think this could be a Laravel 8 issue 🤔
