### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by glennjacobs** [lunarphp/lunar#854]
Laravel 10 comes out today, so we should start the process of making Lunar compatible.

**Comment by glennjacobs** [comment]
@alecritson will we hotfix the current release, or look to introduce this in 0.2 when it comes out?

**Comment by alecritson** [comment]
I thought when we support L10 we'd drop support for L8? I'd have assumed this would be part of `0.3`?

**Comment by glennjacobs** [comment]
And drop support for PHP 8.0

**Comment by glennjacobs** [comment]
We may have to adjust the roadmap to get a 0.3 release out earlier then.

**Comment by sandervankasteel** [comment]
A quick question, just to make sure I interpreted this correctly. 

So the plan is the support Laravel 10 starting with Lunar 0.3 ?

**Comment by glennjacobs** [comment]
Correct, it won't be in 0.2

**Comment by OscarKolsrud** [comment]
@glennjacobs Is there an ETA on the L10 support?

**Comment by OscarKolsrud** [comment]
@glennjacobs Great stuff!

I see that this is marked as Completed, so can it be expected in the coming week?

Really looking forward to utilizing Lunar instead of building my own DIY solution :)

**Comment by glennjacobs** [comment]
> @glennjacobs Great stuff!
> 
> I see that this is marked as Completed, so can it be expected in the coming week?
> 
> Really looking forward to utilizing Lunar instead of building my own DIY solution :)

It's in 0.3.0-alpha already
