### ISSUE TITLE
[Hub] Error on product page after creating product variants

### ISSUE THREAD

**Issue by MaximPixodeo** [lunarphp/lunar#856]
- Lunar version: 0.1.6
- Laravel Version: 9.51.0
- PHP Version: 8.1.13

### Expected Behaviour:

Access the product page : `/hub/products/1`

### Actual Behaviour:

Request return an error 500 : 
![image](https://user-images.githubusercontent.com/89903149/218745309-e4f44ffa-c358-4703-80ca-ae9dbadfbdae.png)

### Steps To Reproduce:

Theses steps were done on the hub's gui, not through the code.

1. Create a new product
2. Create first two product variant attributes `/hub/settings/attributes/productvariant`
3. Acces to the previously product created : `/hub/products/{id}`

**Comment by wychoong** [comment]
did you recently added a new currency and set as default?

**Comment by MaximPixodeo** [comment]
Hello @wychoong,

Indeed, added an '€' currency and setted as default between the steps. 
As the error was concerning the product variant component I didn't think it was linked.

**Comment by wychoong** [comment]
@glennjacobs this sort of related with the issue brought up earlier in #502

**Comment by nafil161** [comment]
I also faced the issue when i created a product and after that created a new currency and set as default. 

After that i remove the product and currency and modified USD currency and kept only one currency

**Comment by alecritson** [comment]
This should no longer be an issue in v1
