### ISSUE TITLE
Full stops in SKUs

### ISSUE THREAD

**Issue by ryanmitchell** [lunarphp/lunar#874]
SKUs on product variants have a validation rule of `alpha_dash` but we have a need to include dots in the SKU based on what a supplier is providing.

Can the validation rule either be updated to accommodate this or can it be extendable to allow the rules to be defined by a dev?

**Comment by glennjacobs** [comment]
Maybe we should allow for more options in the current config? At the moment we allow SKU to be required or not, and unique or not. Guess we could also add the validation type?

Maybe there's a better approach to customising validation long-term, but I guess it would do for now?

**Comment by ryanmitchell** [comment]
Yeah it might be worth letting devs override the alpha_num validation type if they want and let them specify their own validation rules?

**Comment by glennjacobs** [comment]
Yep. If you want to do a PR feel free.

**Comment by alecritson** [comment]
Just to jump in on this, it is actually possible, it's on 0.2 so I don't think it's in the current docs.

```php
Lunar\Hub\Http\Livewire\Components\Products\ProductCreate::extendValidation([
    'variant.sku' => ['required', 'min:8'],
]);

Lunar\Hub\Http\Livewire\Components\Products\ProductShow::extendValidation([
    'variant.sku' => ['required', 'min:8'],
]);

Lunar\Hub\Http\Livewire\Components\Products\Variants\VariantShow::extendValidation([
    'variant.sku' => ['required', 'min:8']
]);
```

**Comment by glennjacobs** [comment]
@alecritson is this in the docs? I had a look at https://docs-next.lunarphp.io/ but can't see it.

**Comment by alecritson** [comment]
Not sure how docs-next works, but docs were added for it on the PR #443

**Comment by ryanmitchell** [comment]
Thanks @alecritson !

**Comment by glennjacobs** [comment]
> Not sure how docs-next works, but docs were added for it on the PR #443

They run off the `0.2` branch.

**Comment by glennjacobs** [comment]
Found it https://github.com/lunarphp/lunar/blob/0.2/docs/src/extending/validations.md

It hasn't been added to the side menu, hence it can't be found.

**Comment by glennjacobs** [comment]
Here we go!

https://docs-next.lunarphp.io/extending/validations.html
