### ISSUE TITLE
Discounts and subtotal

### ISSUE THREAD

**Issue by ryanmitchell** [lunarphp/lunar#875]
On 0.2-rc2 if you have a discount (eg a AmountOff) and its applied, the subTotal on the cart is the amount of the items with the discount removed.

Therefore there is no way of showing what the price was BEFORE the discount was applied.

Usually you would display to the customer:

Subtotal - x
Discount - y
Tax - z
Shipping - zz
Total - xx

Is this intentional or is there a way around this?

**Comment by glennjacobs** [comment]
I'll have a look into this in the morning.

**Comment by ryanmitchell** [comment]
Thanks. It’s totally possible I’m missing something but I couldn’t see a way of getting it other than adding the discount back on which feels wrong.

**Comment by glennjacobs** [comment]
Quite often subtotal is after cart line discounts (technically it should be in accounting terms). But I can see that some might want the figure you mention.

As you say, it's basically subTotal + Discount

I'm not sure we should have a property for this. If anything, it would be a method on the class.

In 0.3 I'm doing a lot of work on pricing as we need to support prices inclusive of tax. So I would prefer to look at this then.

Are you OK for the meantime to simply add them together?

**Comment by ryanmitchell** [comment]
Yep!

**Comment by ryanmitchell** [comment]
Yep!
