### ISSUE TITLE
Use of unsigned ints on order lines and totals

### ISSUE THREAD

**Issue by ryanmitchell** [lunarphp/lunar#893]
We are integrating with Square for Gift cards and when a voucher is applied we're adding a line with a negative value through the use of a meta value and pipeline on the cart. This all works fine.

When we come to create the order, we're having issues with both the order subtotal and line item totals (unit price, line total etc) not allowing negative values. I understand the reasons why on your side, but is this something you'd be open to changing?

For clarification, subtotal can be negative as the gift card is applied across the whole cart value (shipping included).

I'd prefer not to implement this as a `discount` as it's not - its a pre-purchased sum of money that is being applied.

**Comment by ryanmitchell** [comment]
Would be good to hear your thoughts on this @glennjacobs - if its not something you'd want to change then I'll need to come up with a different approach (maybe you've encountered a similar situation on your developments and have handled it differently).

**Comment by glennjacobs** [comment]
@ryanmitchell I'm not keen on allowing negative numbers, my gut says it's wrong.

However, with a gift card, wouldn't that be classified as a payment, rather than an cart/order line?

**Comment by ryanmitchell** [comment]
Thats ok - adding a second payment was my next option, its just going to get messy from a code point of view as there will be 2 transactions.

**Comment by glennjacobs** [comment]
I presume this is it https://squareup.com/gb/en/gift-cards ?

If so, then yes, it should be implemented as a payment, especially as Square are handling the gift card account side of things.
