### ISSUE TITLE
BuyXGetY limitations and qualify products

### ISSUE THREAD

**Issue by ryanmitchell** [lunarphp/lunar#937]
On BuyXGetY discounts there are both limitations (by collection, brand, product) and the ability to select what products qualify.

Unless I'm misunderstanding the intent, this feels a bit redundant (?) as the qualifying products should be the same as the limitations? ie you specify the limitations and if matching products are present, then apply the rewards.

Our client just tried to add a discount and was thrown by this as they expected the limitations to work as I've tried to explain.

**Comment by glennjacobs** [comment]
Imagine the scenario below...

You buy 10 mastic tubes and get a free mastic gun. 

The "Get Y" product(s) are different to those that qualify them in "BuyX".

**Comment by ryanmitchell** [comment]
Yep I understand that but we have Limitations:

<img width="1172" alt="Screenshot 2023-04-05 at 14 25 14" src="https://user-images.githubusercontent.com/51899/230094244-bc355b62-6e0e-47cb-91b5-53f783a22272.png">

and

qualifying products:

<img width="1156" alt="Screenshot 2023-04-05 at 14 25 20" src="https://user-images.githubusercontent.com/51899/230094295-2014b048-143a-470d-a67e-12c6aa64008c.png">

Both of which should be affecting the X part of the equation

**Comment by glennjacobs** [comment]
Ah yes, that is a bit stupid. I don't know why Qualify Products was added, I guess it was before the product limitation was added. 

So we either don't use limitations for this type of discount, OR we use the limitations as what defines the qualifying products.

I would suggest it probably makes more sense for the limitations to be hidden on this discount type.

**Comment by ryanmitchell** [comment]
Its definitely easier to remove limitations, but the downside is that gives you less options for what products qualify - you lose the ability to let collections or brands be part of the discount en-masse.

If youre happy to drop qualifying products I can do the PR for the work required.

**Comment by glennjacobs** [comment]
In terms of the code behind the scenes, I think it makes sense to reuse the Limitations system. However, the wording in the UI may not be ideal. So we may need to have a think there?

@alecritson any reason why @ryanmitchell shouldn't do a PR for this?

**Comment by alecritson** [comment]
Yeah I think limitations is correct, it's just how we show on the UI based on the context. For example with an amount off type I think the wording "Limitations" make sense, but with BuyXGetY "Limitations" doesn't feel right 🤔

**Comment by glennjacobs** [comment]
Hopefully, we can come up with wording that suits both discount types. Will have a think!

**Comment by ryanmitchell** [comment]
Any further thoughts on this one?

**Comment by alecritson** [comment]
@glennjacobs

**Comment by alecritson** [comment]
Closing as this seems to relate to a fairly old release. If this still needs to be address please re open :)
