### ISSUE TITLE
Weird Discounts behaviour

### ISSUE THREAD

**Issue by CWFranklin** [lunarphp/lunar#943]
- Lunar version: 0.2.4
- Laravel Version: 9.52.5
- PHP Version: 8.1.10
- Database Driver & Version: MySQL

### Expected Behaviour:
Able to use `->discount` as per documentation on a CartLine.
Correct discount values calculated. CartLine should be able to use correct value from subTotalDiscounted.
Cart should be able to retrieve globally applied discount totals with `->getApplied()` function.

### Actual Behaviour:
Product worth £14.99 + 20% VAT should display as £17.99 (inc VAT). With a 5% global discount, it should and does display the total as £17.09 (inc VAT) in the Cart.
Calling `->discount` on a CartLine returns null as it does not exist. Calling `->discounts` relationship does exist but returns null.
Cart->discountBreakdown shows the correct total value but the individual line methods seem to return incorrect amounts.
`->getApplied()` returns an empty array even with global discount applied.

### Steps To Reproduce:
Added the following details for a global 5% discount that is automatically applied.

```php
  "name" => "Test Sitewide Discount"
  "handle" => "test_sitewide_discount"
  "coupon" => null
  "type" => "Lunar\DiscountTypes\AmountOff"
  "starts_at" => "2023-04-12 13:00:00"
  "ends_at" => null
  "uses" => 0
  "max_uses" => null
  "max_uses_per_user" => null
  "priority" => 10
  "stop" => 0
  "restriction" => null
  "data" => "{"min_prices": {"GBP": null}, "percentage": "5", "fixed_value": false, "fixed_values": {"GBP": null}}"
```

Add a product worth £14.99 + 20% VAT to cart.

**Comment by alecritson** [comment]
Thanks @CWFranklin, I think the docs were a bit out of date, I've put a PR together to try resolve this: https://github.com/lunarphp/lunar/pull/945
