### ISSUE TITLE
Rename Collection Classes

### ISSUE THREAD

**Issue by ghzb** [lunarphp/lunar#948]
**Is your feature request related to a problem? Please describe.**
Collections conflict with existing Laravel Collections

**Describe the solution you'd like**
Would be nice if the class names for collections and collection groups were renamed to something less conflicting

**Describe alternatives you've considered**
Perhaps it could be called something like  CuratedGroup, Assortment, AssortedGroup, ProductLine, Category, Ensemble, etc.

**Comment by glennjacobs** [comment]
"Collection" is a standard term for the categorisation of e-commerce products. To change the naming now would bring a very big breaking change, but not enough benefit.
