### ISSUE TITLE
wrong product discount priority

### ISSUE THREAD

**Issue by wychoong** [lunarphp/lunar#954]
- Lunar version: 0.3

I have 2 discounts configured in the store
```php
// Discount A
"coupon" => ""
"type" => "Lunar\DiscountTypes\AmountOff"
"priority" => 1
"stop" => 0
"restriction" => null
"data" => "{"percentage":null,"fixed_values":{"MYR":"5.50"},"fixed_value":true,"min_prices":{"MYR":"200"}}"

// Discount B
"coupon" => null
"type" => "Lunar\DiscountTypes\AmountOff"
"priority" => 5
"stop" => 0
"restriction" => null
"data" => "{"percentage":"5","fixed_values":{"MYR":"3"},"fixed_value":true,"min_prices":{"MYR":null}}"
// Discount B is limited to Product A
```

in the cart contains 2 cart line
```php
// Line 1, Product A
+discountTotal: Lunar\DataTypes\Price {#2452 ▼
  +value: 300
}

// Line 2, Product B
+discountTotal: Lunar\DataTypes\Price {#2655 ▼
  +value: 275
}
```

```php
// on the cart 
+discountTotal: Lunar\DataTypes\Price {#2451 ▼
  +value: 575
}
```

### Expected Behaviour:
Discount A is applicable for both product, but Discount B is only for Product A.
So the final discount should be:
Product A: -$3
Product B: -$5.50

or 

Product A: -$3 + -$2.75
Product B: -$2.75

either way discount total = $8.50

### Actual Behaviour:
total discount = $5.75, due to discount B $3 is higher than discount A $5/2

### Possible solution
1. notice that discount is applied in ascending order, which should be applied from high to low ( 1: Low, 5: Medium, 10: High ) https://github.com/lunarphp/lunar/blob/be1c45a50183ce399a3c0fa9f93279bb4f08a494/packages/core/src/Managers/DiscountManager.php#L154
2. apply discount with `Limitations` first

however, the next problem is after the discount overwritten in the cart item, the `cart->discountBreakdown` is still showing the outdated discount, maybe need a `discountBreakdown` on the cart item level too?

**Comment by alecritson** [comment]
I assume this has been completed by your other PR? If there is still a separate issue please open another issue.
