### ISSUE TITLE
Adding custom middleware to hub routes

### ISSUE THREAD

**Issue by nick-nds** [lunarphp/lunar#957]
**Is your feature request related to a problem? Please describe.**
I am trying to add my custom middleware to admin hub routes and I can't find any way to do so.

**Describe the solution you'd like**
Adding an option to config in lunar-hub.system.middleware to add custom middleware will solve this problem.

**Describe alternatives you've considered**
I have also considered adding an artisan command to publish routes will solve this issue and won't disturb the flow of the package.

**Comment by glennjacobs** [comment]
Pretty sure PR #939 provides this

**Comment by nick-nds** [comment]
Thank you.
