### ISSUE TITLE
Using a custom discount type in the admin hub is broken

### ISSUE THREAD

**Issue by ryanmitchell** [lunarphp/lunar#959]
If you make a custom discount type eg something as simple as

```php
<?php
namespace App\Lunar\DiscountTypes;
class AmountOffRetail extends \Lunar\DiscountTypes\AmountOff { }
?>
```

And register it using the Discounts Facade, then try to use it in the Lunar hub you get:

"Call to member function rules() on null" in partials/forms/discount.php coming from AbstractDiscount line 442.

The issue seems to be the hub is using Editing/DiscountTypes as the source of truth for what components are available, not the Discount facade? Maybe each discount needs a getComponent() method, rather than using this?

**Comment by alecritson** [comment]
@ryanmitchell Yeah so there's a two step process, one register the discount type with the core and then register with the admin hub, it wasn't actually possible to do that yet (the hub side) but i've put together a quick PR which should help this.

**Comment by ryanmitchell** [comment]
Thats great, thanks!
